/*
 * Firefly III API v2.0.0
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-03-05T14:16:31+00:00 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FireflyIIINet.Model;
using FireflyIIINet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FireflyIIINet.Test.Model
{
    /// <summary>
    ///  Class for testing AutocompleteObjectGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AutocompleteObjectGroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AutocompleteObjectGroup
        //private AutocompleteObjectGroup instance;

        public AutocompleteObjectGroupTests()
        {
            // TODO uncomment below to create an instance of AutocompleteObjectGroup
            //instance = new AutocompleteObjectGroup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutocompleteObjectGroup
        /// </summary>
        [Fact]
        public void AutocompleteObjectGroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" AutocompleteObjectGroup
            //Assert.IsType<AutocompleteObjectGroup>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
