/*
 * Firefly III API v2.0.0
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-03-05T14:16:31+00:00 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FireflyIIINet.Model;
using FireflyIIINet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FireflyIIINet.Test.Model
{
    /// <summary>
    ///  Class for testing Bill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Bill
        //private Bill instance;

        public BillTests()
        {
            // TODO uncomment below to create an instance of Bill
            //instance = new Bill();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Bill
        /// </summary>
        [Fact]
        public void BillInstanceTest()
        {
            // TODO uncomment below to test "IsType" Bill
            //Assert.IsType<Bill>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Fact]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }

        /// <summary>
        /// Test the property 'CurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void CurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'CurrencyDecimalPlaces'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AmountMin'
        /// </summary>
        [Fact]
        public void AmountMinTest()
        {
            // TODO unit test for the property 'AmountMin'
        }

        /// <summary>
        /// Test the property 'AmountMax'
        /// </summary>
        [Fact]
        public void AmountMaxTest()
        {
            // TODO unit test for the property 'AmountMax'
        }

        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

        /// <summary>
        /// Test the property 'ExtensionDate'
        /// </summary>
        [Fact]
        public void ExtensionDateTest()
        {
            // TODO unit test for the property 'ExtensionDate'
        }

        /// <summary>
        /// Test the property 'RepeatFreq'
        /// </summary>
        [Fact]
        public void RepeatFreqTest()
        {
            // TODO unit test for the property 'RepeatFreq'
        }

        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Fact]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'NextExpectedMatch'
        /// </summary>
        [Fact]
        public void NextExpectedMatchTest()
        {
            // TODO unit test for the property 'NextExpectedMatch'
        }

        /// <summary>
        /// Test the property 'NextExpectedMatchDiff'
        /// </summary>
        [Fact]
        public void NextExpectedMatchDiffTest()
        {
            // TODO unit test for the property 'NextExpectedMatchDiff'
        }

        /// <summary>
        /// Test the property 'ObjectGroupId'
        /// </summary>
        [Fact]
        public void ObjectGroupIdTest()
        {
            // TODO unit test for the property 'ObjectGroupId'
        }

        /// <summary>
        /// Test the property 'ObjectGroupOrder'
        /// </summary>
        [Fact]
        public void ObjectGroupOrderTest()
        {
            // TODO unit test for the property 'ObjectGroupOrder'
        }

        /// <summary>
        /// Test the property 'ObjectGroupTitle'
        /// </summary>
        [Fact]
        public void ObjectGroupTitleTest()
        {
            // TODO unit test for the property 'ObjectGroupTitle'
        }

        /// <summary>
        /// Test the property 'PayDates'
        /// </summary>
        [Fact]
        public void PayDatesTest()
        {
            // TODO unit test for the property 'PayDates'
        }

        /// <summary>
        /// Test the property 'PaidDates'
        /// </summary>
        [Fact]
        public void PaidDatesTest()
        {
            // TODO unit test for the property 'PaidDates'
        }
    }
}
