/*
 * Firefly III API v2.0.0
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-03-05T14:16:31+00:00 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FireflyIIINet.Model;
using FireflyIIINet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FireflyIIINet.Test.Model
{
    /// <summary>
    ///  Class for testing BudgetSpent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BudgetSpentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BudgetSpent
        //private BudgetSpent instance;

        public BudgetSpentTests()
        {
            // TODO uncomment below to create an instance of BudgetSpent
            //instance = new BudgetSpent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BudgetSpent
        /// </summary>
        [Fact]
        public void BudgetSpentInstanceTest()
        {
            // TODO uncomment below to test "IsType" BudgetSpent
            //Assert.IsType<BudgetSpent>(instance);
        }

        /// <summary>
        /// Test the property 'Sum'
        /// </summary>
        [Fact]
        public void SumTest()
        {
            // TODO unit test for the property 'Sum'
        }

        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Fact]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }

        /// <summary>
        /// Test the property 'CurrencyDecimalPlaces'
        /// </summary>
        [Fact]
        public void CurrencyDecimalPlacesTest()
        {
            // TODO unit test for the property 'CurrencyDecimalPlaces'
        }
    }
}
