/*
 * Firefly III API v2.0.0
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2023-03-05T14:16:31+00:00 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FireflyIIINet.Model;
using FireflyIIINet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FireflyIIINet.Test.Model
{
    /// <summary>
    ///  Class for testing Unauthenticated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnauthenticatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Unauthenticated
        //private Unauthenticated instance;

        public UnauthenticatedTests()
        {
            // TODO uncomment below to create an instance of Unauthenticated
            //instance = new Unauthenticated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Unauthenticated
        /// </summary>
        [Fact]
        public void UnauthenticatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" Unauthenticated
            //Assert.IsType<Unauthenticated>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Exception'
        /// </summary>
        [Fact]
        public void ExceptionTest()
        {
            // TODO unit test for the property 'Exception'
        }
    }
}
