# To generate the client:
# npx @openapitools/openapi-generator-cli generate -c openapi-dotnet.yaml

inputSpec: api-yaml/firefly-iii-2.0.2.yaml
generatorName: csharp
outputDir: generated/
packageName: FireflyIIINet
packageVersion: 2.0.2.1
targetFramework: net6.0
templateDir: out