# To generate the client:
# npx @openapitools/openapi-generator-cli generate -c openapi-dotnet.yaml

# To build & pack for Nuget
# (TODO Move this into a github action - preferably along with generation)
# dotnet pack -c Release -p:PackageVersion=0.1.0 -p:PackageLicenseExpression=MIT .\generated\src\FireflyIII\FireflyIII.csproj

inputSpec: api-yaml/firefly-iii-1.4.0.yaml
generatorName: csharp
outputDir: generated/
packageName: FireflyIIINet
packageVersion: 1.4.0
targetFramework: netstandard2.0 # is only on lang version C# 7.3
#nullableReferenceTypes: true # must be lang version > C# 8.0