# To generate the client:
# npx @openapitools/openapi-generator-cli generate -c openapi-dotnet.yaml

# To build & pack for Nuget
# (TODO Move this into a github action - preferably along with generation)
# dotnet pack -c Release -p:PackageVersion=0.1.0 -p:PackageLicenseExpression=MIT .\generated\src\FireflyIII\FireflyIII.csproj

inputSpec: api-yaml/firefly-iii-2.0.0.yaml
generatorName: csharp
outputDir: generated/
packageName: FireflyIIINet
packageVersion: 2.0.0.1
targetFramework: net6.0
templateDir: out