/*
 * Firefly III API v6.4.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-10-28 @ 09:59:50 (Europe/Amsterdam) 
 *
 * The version of the OpenAPI document: 6.4.2
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// AccountProperties
    /// </summary>
    [DataContract(Name = "AccountProperties")]
    public partial class AccountProperties : IEquatable<AccountProperties>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("type")]
        public ShortAccountTypeProperty Type { get; set; }

        /// <summary>
        /// Gets or Sets AccountRole
        /// </summary>
        [DataMember(Name = "account_role", EmitDefaultValue = false)]
        [JsonPropertyName("account_role")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AccountRoleProperty? AccountRole { get; set; }

        /// <summary>
        /// Gets or Sets CreditCardTypeProperty
        /// </summary>
        [DataMember(Name = "credit_card_type", EmitDefaultValue = false)]
        [JsonPropertyName("credit_card_type")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public CreditCardTypeProperty? CreditCardTypeProperty { get; set; }

        /// <summary>
        /// Gets or Sets LiabilityTypeProperty
        /// </summary>
        [DataMember(Name = "liability_type", EmitDefaultValue = false)]
        [JsonPropertyName("liability_type")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public LiabilityTypeProperty? LiabilityTypeProperty { get; set; }

        /// <summary>
        /// Gets or Sets LiabilityDirectionProperty
        /// </summary>
        [DataMember(Name = "liability_direction", EmitDefaultValue = false)]
        [JsonPropertyName("liability_direction")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public LiabilityDirectionProperty? LiabilityDirectionProperty { get; set; }

        /// <summary>
        /// Gets or Sets InterestPeriodProperty
        /// </summary>
        [DataMember(Name = "interest_period", EmitDefaultValue = false)]
        [JsonPropertyName("interest_period")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public InterestPeriodProperty? InterestPeriodProperty { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountProperties" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountProperties() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountProperties" /> class.
        /// </summary>
        /// <param name="active">active (default to true).</param>
        /// <param name="order">Order of the account. Is NULL if account is not asset or liability..</param>
        /// <param name="name">name (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="accountRole">accountRole.</param>
        /// <param name="objectGroupId">The group ID of the group this object is part of. NULL if no group..</param>
        /// <param name="objectGroupTitle">The name of the group. NULL if no group..</param>
        /// <param name="currencyId">The currency ID of the currency associated with this object..</param>
        /// <param name="currencyName">The currency name of the currency associated with this object..</param>
        /// <param name="currencyCode">The currency code of the currency associated with this object..</param>
        /// <param name="openingBalance">Represents the opening balance, the initial amount this account holds in the currency of the account or the administration&#39;s primary currency if the account has no currency..</param>
        /// <param name="pcOpeningBalance">The opening balance of the account in the administration&#39;s primary currency (pc)..</param>
        /// <param name="virtualBalance">The virtual balance of the account in the account&#39;s currency or the administration&#39;s primary currency if the account has no currency..</param>
        /// <param name="pcVirtualBalance">The virtual balance of the account in the administration&#39;s primary currency (pc)..</param>
        /// <param name="debtAmount">In liability accounts (loans, debts and mortgages), this is the amount of debt in the account&#39;s currency. In asset accounts, this is NULL..</param>
        /// <param name="pcDebtAmount">In liability accounts (loans, debts and mortgages), this is the amount of debt in the administration&#39;s primary currency. In asset accounts, this is NULL..</param>
        /// <param name="notes">notes.</param>
        /// <param name="monthlyPaymentDate">Mandatory when the account_role is ccAsset. Moment at which CC payment installments are asked for by the bank..</param>
        /// <param name="creditCardType">creditCardType.</param>
        /// <param name="accountNumber">accountNumber.</param>
        /// <param name="iban">iban.</param>
        /// <param name="bic">bic.</param>
        /// <param name="openingBalanceDate">Represents the date of the opening balance..</param>
        /// <param name="liabilityType">liabilityType.</param>
        /// <param name="liabilityDirection">liabilityDirection.</param>
        /// <param name="interest">Mandatory when type is liability. Interest percentage..</param>
        /// <param name="interestPeriod">interestPeriod.</param>
        /// <param name="includeNetWorth">includeNetWorth (default to true).</param>
        /// <param name="longitude">Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map..</param>
        /// <param name="latitude">Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map..</param>
        /// <param name="zoomLevel">Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels..</param>
        /// <param name="lastActivity">Last activity of the account..</param>
        public AccountProperties(bool active = true, int? order = default(int?), string name = default(string), ShortAccountTypeProperty type = default(ShortAccountTypeProperty), AccountRoleProperty? accountRole = default(AccountRoleProperty?), string objectGroupId = default(string), string objectGroupTitle = default(string), string currencyId = default(string), string currencyName = default(string), string currencyCode = default(string), string openingBalance = default(string), string pcOpeningBalance = default(string), string virtualBalance = default(string), string pcVirtualBalance = default(string), string debtAmount = default(string), string pcDebtAmount = default(string), string notes = default(string), DateTime? monthlyPaymentDate = default(DateTime?), CreditCardTypeProperty? creditCardType = default(CreditCardTypeProperty?), string accountNumber = default(string), string iban = default(string), string bic = default(string), DateTime? openingBalanceDate = default(DateTime?), LiabilityTypeProperty? liabilityType = default(LiabilityTypeProperty?), LiabilityDirectionProperty? liabilityDirection = default(LiabilityDirectionProperty?), string interest = default(string), InterestPeriodProperty? interestPeriod = default(InterestPeriodProperty?), bool includeNetWorth = true, double? longitude = default(double?), double? latitude = default(double?), int? zoomLevel = default(int?), DateTime? lastActivity = default(DateTime?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AccountProperties and cannot be null");
            }
            Name = name;
            Type = type;
            Active = active;
            Order = order;
            AccountRole = accountRole;
            ObjectGroupId = objectGroupId;
            ObjectGroupTitle = objectGroupTitle;
            CurrencyId = currencyId;
            CurrencyName = currencyName;
            CurrencyCode = currencyCode;
            OpeningBalance = openingBalance;
            PcOpeningBalance = pcOpeningBalance;
            VirtualBalance = virtualBalance;
            PcVirtualBalance = pcVirtualBalance;
            DebtAmount = debtAmount;
            PcDebtAmount = pcDebtAmount;
            Notes = notes;
            MonthlyPaymentDate = monthlyPaymentDate;
            CreditCardTypeProperty = creditCardType;
            AccountNumber = accountNumber;
            Iban = iban;
            Bic = bic;
            OpeningBalanceDate = openingBalanceDate;
            LiabilityTypeProperty = liabilityType;
            LiabilityDirectionProperty = liabilityDirection;
            Interest = interest;
            InterestPeriodProperty = interestPeriod;
            IncludeNetWorth = includeNetWorth;
            Longitude = longitude;
            Latitude = latitude;
            ZoomLevel = zoomLevel;
            LastActivity = lastActivity;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        [JsonPropertyName("created_at")]
        [JsonInclude]
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Returns false as CreatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = true)]
        [JsonPropertyName("updated_at")]
        [JsonInclude]
        public DateTime UpdatedAt { get; private set; }

        /// <summary>
        /// Returns false as UpdatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "active", EmitDefaultValue = true)]
        [JsonPropertyName("active")]
        public bool Active { get; set; }

        /// <summary>
        /// Order of the account. Is NULL if account is not asset or liability.
        /// </summary>
        /// <value>Order of the account. Is NULL if account is not asset or liability.</value>
        /// <example>1</example>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        [JsonPropertyName("order")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? Order { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>My checking account</example>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// The group ID of the group this object is part of. NULL if no group.
        /// </summary>
        /// <value>The group ID of the group this object is part of. NULL if no group.</value>
        /// <example>5</example>
        [DataMember(Name = "object_group_id", EmitDefaultValue = false)]
        [JsonPropertyName("object_group_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ObjectGroupId { get; set; }

        /// <summary>
        /// The order of the group. At least 1, for the highest sorting.
        /// </summary>
        /// <value>The order of the group. At least 1, for the highest sorting.</value>
        /// <example>5</example>
        [DataMember(Name = "object_group_order", EmitDefaultValue = false)]
        [JsonPropertyName("object_group_order")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public int? ObjectGroupOrder { get; private set; }

        /// <summary>
        /// Returns false as ObjectGroupOrder should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeObjectGroupOrder()
        {
            return false;
        }
        /// <summary>
        /// The name of the group. NULL if no group.
        /// </summary>
        /// <value>The name of the group. NULL if no group.</value>
        /// <example>Example Group</example>
        [DataMember(Name = "object_group_title", EmitDefaultValue = false)]
        [JsonPropertyName("object_group_title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ObjectGroupTitle { get; set; }

        /// <summary>
        /// Indicates whether the account has a currency setting. If false, the account uses the administration&#39;s primary currency. Asset accounts and liability accounts always have a currency setting, while expense and revenue accounts do not.
        /// </summary>
        /// <value>Indicates whether the account has a currency setting. If false, the account uses the administration&#39;s primary currency. Asset accounts and liability accounts always have a currency setting, while expense and revenue accounts do not.</value>
        /// <example>true</example>
        [DataMember(Name = "object_has_currency_setting", EmitDefaultValue = true)]
        [JsonPropertyName("object_has_currency_setting")]
        [JsonInclude]
        public bool ObjectHasCurrencySetting { get; private set; }

        /// <summary>
        /// Returns false as ObjectHasCurrencySetting should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeObjectHasCurrencySetting()
        {
            return false;
        }
        /// <summary>
        /// The currency ID of the currency associated with this object.
        /// </summary>
        /// <value>The currency ID of the currency associated with this object.</value>
        /// <example>5</example>
        [DataMember(Name = "currency_id", EmitDefaultValue = true)]
        [JsonPropertyName("currency_id")]
        public string CurrencyId { get; set; }

        /// <summary>
        /// The currency name of the currency associated with this object.
        /// </summary>
        /// <value>The currency name of the currency associated with this object.</value>
        /// <example>Euro</example>
        [DataMember(Name = "currency_name", EmitDefaultValue = true)]
        [JsonPropertyName("currency_name")]
        public string CurrencyName { get; set; }

        /// <summary>
        /// The currency code of the currency associated with this object.
        /// </summary>
        /// <value>The currency code of the currency associated with this object.</value>
        /// <example>EUR</example>
        [DataMember(Name = "currency_code", EmitDefaultValue = true)]
        [JsonPropertyName("currency_code")]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets CurrencySymbol
        /// </summary>
        /// <example>$</example>
        [DataMember(Name = "currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("currency_symbol")]
        [JsonInclude]
        public string CurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as CurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets CurrencyDecimalPlaces
        /// </summary>
        /// <example>2</example>
        [DataMember(Name = "currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("currency_decimal_places")]
        [JsonInclude]
        public int CurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as CurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// The currency ID of the administration&#39;s primary currency.
        /// </summary>
        /// <value>The currency ID of the administration&#39;s primary currency.</value>
        /// <example>5</example>
        [DataMember(Name = "primary_currency_id", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_id")]
        [JsonInclude]
        public string PrimaryCurrencyId { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyId()
        {
            return false;
        }
        /// <summary>
        /// The currency name of the administration&#39;s primary currency.
        /// </summary>
        /// <value>The currency name of the administration&#39;s primary currency.</value>
        /// <example>Euro</example>
        [DataMember(Name = "primary_currency_name", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_name")]
        [JsonInclude]
        public string PrimaryCurrencyName { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyName()
        {
            return false;
        }
        /// <summary>
        /// The currency code of the administration&#39;s primary currency.
        /// </summary>
        /// <value>The currency code of the administration&#39;s primary currency.</value>
        /// <example>EUR</example>
        [DataMember(Name = "primary_currency_code", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_code")]
        [JsonInclude]
        public string PrimaryCurrencyCode { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyCode should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyCode()
        {
            return false;
        }
        /// <summary>
        /// The currency symbol of the administration&#39;s primary currency.
        /// </summary>
        /// <value>The currency symbol of the administration&#39;s primary currency.</value>
        /// <example>$</example>
        [DataMember(Name = "primary_currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_symbol")]
        [JsonInclude]
        public string PrimaryCurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// The currency decimal places of the administration&#39;s primary currency.
        /// </summary>
        /// <value>The currency decimal places of the administration&#39;s primary currency.</value>
        /// <example>2</example>
        [DataMember(Name = "primary_currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_decimal_places")]
        [JsonInclude]
        public int PrimaryCurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// The current balance of the account in the account&#39;s currency. If the account has no currency, this is the balance in the administration&#39;s primary currency. Either way, the &#x60;currency_*&#x60; fields reflect the currency used.
        /// </summary>
        /// <value>The current balance of the account in the account&#39;s currency. If the account has no currency, this is the balance in the administration&#39;s primary currency. Either way, the &#x60;currency_*&#x60; fields reflect the currency used.</value>
        /// <example>123.45</example>
        [DataMember(Name = "current_balance", EmitDefaultValue = true)]
        [JsonPropertyName("current_balance")]
        [JsonInclude]
        public string CurrentBalance { get; private set; }

        /// <summary>
        /// Returns false as CurrentBalance should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrentBalance()
        {
            return false;
        }
        /// <summary>
        /// The current balance of the account in the administration&#39;s primary currency. The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.
        /// </summary>
        /// <value>The current balance of the account in the administration&#39;s primary currency. The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.</value>
        /// <example>123.45</example>
        [DataMember(Name = "pc_current_balance", EmitDefaultValue = false)]
        [JsonPropertyName("pc_current_balance")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string PcCurrentBalance { get; private set; }

        /// <summary>
        /// Returns false as PcCurrentBalance should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePcCurrentBalance()
        {
            return false;
        }
        /// <summary>
        /// If you submit a start AND end date, this will be the difference between those two moments.
        /// </summary>
        /// <value>If you submit a start AND end date, this will be the difference between those two moments.</value>
        /// <example>123.45</example>
        [DataMember(Name = "balance_difference", EmitDefaultValue = true)]
        [JsonPropertyName("balance_difference")]
        [JsonInclude]
        public string BalanceDifference { get; private set; }

        /// <summary>
        /// Returns false as BalanceDifference should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBalanceDifference()
        {
            return false;
        }
        /// <summary>
        /// If you submit a start AND end date, this will be the difference in the currency of the account or the administration&#39;s primary currency between those two moments.
        /// </summary>
        /// <value>If you submit a start AND end date, this will be the difference in the currency of the account or the administration&#39;s primary currency between those two moments.</value>
        /// <example>123.45</example>
        [DataMember(Name = "pc_balance_difference", EmitDefaultValue = false)]
        [JsonPropertyName("pc_balance_difference")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string PcBalanceDifference { get; private set; }

        /// <summary>
        /// Returns false as PcBalanceDifference should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePcBalanceDifference()
        {
            return false;
        }
        /// <summary>
        /// Represents the opening balance, the initial amount this account holds in the currency of the account or the administration&#39;s primary currency if the account has no currency. Either way, the &#x60;currency_*&#x60; fields reflect the currency used.
        /// </summary>
        /// <value>Represents the opening balance, the initial amount this account holds in the currency of the account or the administration&#39;s primary currency if the account has no currency. Either way, the &#x60;currency_*&#x60; fields reflect the currency used.</value>
        /// <example>-1012.12</example>
        [DataMember(Name = "opening_balance", EmitDefaultValue = true)]
        [JsonPropertyName("opening_balance")]
        public string OpeningBalance { get; set; }

        /// <summary>
        /// The opening balance of the account in the administration&#39;s primary currency (pc). The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.
        /// </summary>
        /// <value>The opening balance of the account in the administration&#39;s primary currency (pc). The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.</value>
        /// <example>-1012.12</example>
        [DataMember(Name = "pc_opening_balance", EmitDefaultValue = true)]
        [JsonPropertyName("pc_opening_balance")]
        public string PcOpeningBalance { get; set; }

        /// <summary>
        /// The virtual balance of the account in the account&#39;s currency or the administration&#39;s primary currency if the account has no currency.
        /// </summary>
        /// <value>The virtual balance of the account in the account&#39;s currency or the administration&#39;s primary currency if the account has no currency.</value>
        /// <example>123.45</example>
        [DataMember(Name = "virtual_balance", EmitDefaultValue = true)]
        [JsonPropertyName("virtual_balance")]
        public string VirtualBalance { get; set; }

        /// <summary>
        /// The virtual balance of the account in the administration&#39;s primary currency (pc). The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.
        /// </summary>
        /// <value>The virtual balance of the account in the administration&#39;s primary currency (pc). The &#x60;primary_currency_*&#x60; fields reflect the currency used. This field is NULL if the user does have &#39;convert to primary&#39; set to true in their settings.</value>
        /// <example>123.45</example>
        [DataMember(Name = "pc_virtual_balance", EmitDefaultValue = true)]
        [JsonPropertyName("pc_virtual_balance")]
        public string PcVirtualBalance { get; set; }

        /// <summary>
        /// In liability accounts (loans, debts and mortgages), this is the amount of debt in the account&#39;s currency (see the &#x60;currency_*&#x60; fields). In asset accounts, this is NULL.
        /// </summary>
        /// <value>In liability accounts (loans, debts and mortgages), this is the amount of debt in the account&#39;s currency (see the &#x60;currency_*&#x60; fields). In asset accounts, this is NULL.</value>
        /// <example>1012.12</example>
        [DataMember(Name = "debt_amount", EmitDefaultValue = false)]
        [JsonPropertyName("debt_amount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string DebtAmount { get; set; }

        /// <summary>
        /// In liability accounts (loans, debts and mortgages), this is the amount of debt in the administration&#39;s primary currency (see the &#x60;currency_*&#x60; fields. In asset accounts, this is NULL.
        /// </summary>
        /// <value>In liability accounts (loans, debts and mortgages), this is the amount of debt in the administration&#39;s primary currency (see the &#x60;currency_*&#x60; fields. In asset accounts, this is NULL.</value>
        /// <example>1012.12</example>
        [DataMember(Name = "pc_debt_amount", EmitDefaultValue = false)]
        [JsonPropertyName("pc_debt_amount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string PcDebtAmount { get; set; }

        /// <summary>
        /// The timestamp for this date is always 23:59:59, to indicate it&#39;s the balance at the very END of that particular day.
        /// </summary>
        /// <value>The timestamp for this date is always 23:59:59, to indicate it&#39;s the balance at the very END of that particular day.</value>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "current_balance_date", EmitDefaultValue = true)]
        [JsonPropertyName("current_balance_date")]
        [JsonInclude]
        public DateTime CurrentBalanceDate { get; private set; }

        /// <summary>
        /// Returns false as CurrentBalanceDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrentBalanceDate()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        /// <example>Some example notes</example>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        [JsonPropertyName("notes")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Notes { get; set; }

        /// <summary>
        /// Mandatory when the account_role is ccAsset. Moment at which CC payment installments are asked for by the bank.
        /// </summary>
        /// <value>Mandatory when the account_role is ccAsset. Moment at which CC payment installments are asked for by the bank.</value>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "monthly_payment_date", EmitDefaultValue = false)]
        [JsonPropertyName("monthly_payment_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? MonthlyPaymentDate { get; set; }

        /// <summary>
        /// Gets or Sets AccountNumber
        /// </summary>
        /// <example>7009312345678</example>
        [DataMember(Name = "account_number", EmitDefaultValue = false)]
        [JsonPropertyName("account_number")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or Sets Iban
        /// </summary>
        /// <example>GB98MIDL07009312345678</example>
        [DataMember(Name = "iban", EmitDefaultValue = false)]
        [JsonPropertyName("iban")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Iban { get; set; }

        /// <summary>
        /// Gets or Sets Bic
        /// </summary>
        /// <example>BOFAUS3N</example>
        [DataMember(Name = "bic", EmitDefaultValue = false)]
        [JsonPropertyName("bic")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Bic { get; set; }

        /// <summary>
        /// Represents the date of the opening balance.
        /// </summary>
        /// <value>Represents the date of the opening balance.</value>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "opening_balance_date", EmitDefaultValue = false)]
        [JsonPropertyName("opening_balance_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? OpeningBalanceDate { get; set; }

        /// <summary>
        /// Mandatory when type is liability. Interest percentage.
        /// </summary>
        /// <value>Mandatory when type is liability. Interest percentage.</value>
        /// <example>5.3</example>
        [DataMember(Name = "interest", EmitDefaultValue = false)]
        [JsonPropertyName("interest")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Interest { get; set; }

        /// <summary>
        /// Gets or Sets IncludeNetWorth
        /// </summary>
        /// <example>true</example>
        [DataMember(Name = "include_net_worth", EmitDefaultValue = true)]
        [JsonPropertyName("include_net_worth")]
        public bool IncludeNetWorth { get; set; }

        /// <summary>
        /// Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map.
        /// </summary>
        /// <value>Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map.</value>
        /// <example>5.916667</example>
        [DataMember(Name = "longitude", EmitDefaultValue = false)]
        [JsonPropertyName("longitude")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public double? Longitude { get; set; }

        /// <summary>
        /// Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map.
        /// </summary>
        /// <value>Latitude of the accounts&#39;s location, if applicable. Can be used to draw a map.</value>
        /// <example>51.983333</example>
        [DataMember(Name = "latitude", EmitDefaultValue = false)]
        [JsonPropertyName("latitude")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public double? Latitude { get; set; }

        /// <summary>
        /// Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.
        /// </summary>
        /// <value>Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.</value>
        /// <example>6</example>
        [DataMember(Name = "zoom_level", EmitDefaultValue = false)]
        [JsonPropertyName("zoom_level")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? ZoomLevel { get; set; }

        /// <summary>
        /// Last activity of the account.
        /// </summary>
        /// <value>Last activity of the account.</value>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "last_activity", EmitDefaultValue = false)]
        [JsonPropertyName("last_activity")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? LastActivity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountProperties {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  AccountRole: ").Append(AccountRole).Append("\n");
            sb.Append("  ObjectGroupId: ").Append(ObjectGroupId).Append("\n");
            sb.Append("  ObjectGroupOrder: ").Append(ObjectGroupOrder).Append("\n");
            sb.Append("  ObjectGroupTitle: ").Append(ObjectGroupTitle).Append("\n");
            sb.Append("  ObjectHasCurrencySetting: ").Append(ObjectHasCurrencySetting).Append("\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  CurrencyName: ").Append(CurrencyName).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  CurrencySymbol: ").Append(CurrencySymbol).Append("\n");
            sb.Append("  CurrencyDecimalPlaces: ").Append(CurrencyDecimalPlaces).Append("\n");
            sb.Append("  PrimaryCurrencyId: ").Append(PrimaryCurrencyId).Append("\n");
            sb.Append("  PrimaryCurrencyName: ").Append(PrimaryCurrencyName).Append("\n");
            sb.Append("  PrimaryCurrencyCode: ").Append(PrimaryCurrencyCode).Append("\n");
            sb.Append("  PrimaryCurrencySymbol: ").Append(PrimaryCurrencySymbol).Append("\n");
            sb.Append("  PrimaryCurrencyDecimalPlaces: ").Append(PrimaryCurrencyDecimalPlaces).Append("\n");
            sb.Append("  CurrentBalance: ").Append(CurrentBalance).Append("\n");
            sb.Append("  PcCurrentBalance: ").Append(PcCurrentBalance).Append("\n");
            sb.Append("  BalanceDifference: ").Append(BalanceDifference).Append("\n");
            sb.Append("  PcBalanceDifference: ").Append(PcBalanceDifference).Append("\n");
            sb.Append("  OpeningBalance: ").Append(OpeningBalance).Append("\n");
            sb.Append("  PcOpeningBalance: ").Append(PcOpeningBalance).Append("\n");
            sb.Append("  VirtualBalance: ").Append(VirtualBalance).Append("\n");
            sb.Append("  PcVirtualBalance: ").Append(PcVirtualBalance).Append("\n");
            sb.Append("  DebtAmount: ").Append(DebtAmount).Append("\n");
            sb.Append("  PcDebtAmount: ").Append(PcDebtAmount).Append("\n");
            sb.Append("  CurrentBalanceDate: ").Append(CurrentBalanceDate).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  MonthlyPaymentDate: ").Append(MonthlyPaymentDate).Append("\n");
            sb.Append("  CreditCardTypeProperty: ").Append(CreditCardTypeProperty).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  Iban: ").Append(Iban).Append("\n");
            sb.Append("  Bic: ").Append(Bic).Append("\n");
            sb.Append("  OpeningBalanceDate: ").Append(OpeningBalanceDate).Append("\n");
            sb.Append("  LiabilityTypeProperty: ").Append(LiabilityTypeProperty).Append("\n");
            sb.Append("  LiabilityDirectionProperty: ").Append(LiabilityDirectionProperty).Append("\n");
            sb.Append("  Interest: ").Append(Interest).Append("\n");
            sb.Append("  InterestPeriodProperty: ").Append(InterestPeriodProperty).Append("\n");
            sb.Append("  IncludeNetWorth: ").Append(IncludeNetWorth).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  ZoomLevel: ").Append(ZoomLevel).Append("\n");
            sb.Append("  LastActivity: ").Append(LastActivity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, FireflyIIINet.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AccountProperties);
        }

        /// <summary>
        /// Returns true if AccountProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountProperties input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    CreatedAt == input.CreatedAt ||
					CreatedAt.Equals(input.CreatedAt)
                ) &&
                (
                    UpdatedAt == input.UpdatedAt ||
					UpdatedAt.Equals(input.UpdatedAt)
                ) &&
                (
                    Active == input.Active ||
                    Active.Equals(input.Active)
                ) &&
                (
                    Order == input.Order ||
                    (Order != null &&
                    Order.Equals(input.Order))
                ) &&
                (
                    Name == input.Name ||
					Name.Equals(input.Name)
                ) &&
                (
                    Type == input.Type ||
                    Type.Equals(input.Type)
                ) &&
                (
                    AccountRole == input.AccountRole ||
                    AccountRole.Equals(input.AccountRole)
                ) &&
                (
                    ObjectGroupId == input.ObjectGroupId ||
                    (ObjectGroupId != null &&
                    ObjectGroupId.Equals(input.ObjectGroupId))
                ) &&
                (
                    ObjectGroupOrder == input.ObjectGroupOrder ||
                    (ObjectGroupOrder != null &&
                    ObjectGroupOrder.Equals(input.ObjectGroupOrder))
                ) &&
                (
                    ObjectGroupTitle == input.ObjectGroupTitle ||
                    (ObjectGroupTitle != null &&
                    ObjectGroupTitle.Equals(input.ObjectGroupTitle))
                ) &&
                (
                    ObjectHasCurrencySetting == input.ObjectHasCurrencySetting ||
                    ObjectHasCurrencySetting.Equals(input.ObjectHasCurrencySetting)
                ) &&
                (
                    CurrencyId == input.CurrencyId ||
					CurrencyId.Equals(input.CurrencyId)
                ) &&
                (
                    CurrencyName == input.CurrencyName ||
					CurrencyName.Equals(input.CurrencyName)
                ) &&
                (
                    CurrencyCode == input.CurrencyCode ||
					CurrencyCode.Equals(input.CurrencyCode)
                ) &&
                (
                    CurrencySymbol == input.CurrencySymbol ||
					CurrencySymbol.Equals(input.CurrencySymbol)
                ) &&
                (
                    CurrencyDecimalPlaces == input.CurrencyDecimalPlaces ||
                    CurrencyDecimalPlaces.Equals(input.CurrencyDecimalPlaces)
                ) &&
                (
                    PrimaryCurrencyId == input.PrimaryCurrencyId ||
                    (PrimaryCurrencyId != null &&
                    PrimaryCurrencyId.Equals(input.PrimaryCurrencyId))
                ) &&
                (
                    PrimaryCurrencyName == input.PrimaryCurrencyName ||
                    (PrimaryCurrencyName != null &&
                    PrimaryCurrencyName.Equals(input.PrimaryCurrencyName))
                ) &&
                (
                    PrimaryCurrencyCode == input.PrimaryCurrencyCode ||
                    (PrimaryCurrencyCode != null &&
                    PrimaryCurrencyCode.Equals(input.PrimaryCurrencyCode))
                ) &&
                (
                    PrimaryCurrencySymbol == input.PrimaryCurrencySymbol ||
                    (PrimaryCurrencySymbol != null &&
                    PrimaryCurrencySymbol.Equals(input.PrimaryCurrencySymbol))
                ) &&
                (
                    PrimaryCurrencyDecimalPlaces == input.PrimaryCurrencyDecimalPlaces ||
                    PrimaryCurrencyDecimalPlaces.Equals(input.PrimaryCurrencyDecimalPlaces)
                ) &&
                (
                    CurrentBalance == input.CurrentBalance ||
					CurrentBalance.Equals(input.CurrentBalance)
                ) &&
                (
                    PcCurrentBalance == input.PcCurrentBalance ||
                    (PcCurrentBalance != null &&
                    PcCurrentBalance.Equals(input.PcCurrentBalance))
                ) &&
                (
                    BalanceDifference == input.BalanceDifference ||
                    (BalanceDifference != null &&
                    BalanceDifference.Equals(input.BalanceDifference))
                ) &&
                (
                    PcBalanceDifference == input.PcBalanceDifference ||
                    (PcBalanceDifference != null &&
                    PcBalanceDifference.Equals(input.PcBalanceDifference))
                ) &&
                (
                    OpeningBalance == input.OpeningBalance ||
					OpeningBalance.Equals(input.OpeningBalance)
                ) &&
                (
                    PcOpeningBalance == input.PcOpeningBalance ||
					PcOpeningBalance.Equals(input.PcOpeningBalance)
                ) &&
                (
                    VirtualBalance == input.VirtualBalance ||
					VirtualBalance.Equals(input.VirtualBalance)
                ) &&
                (
                    PcVirtualBalance == input.PcVirtualBalance ||
					PcVirtualBalance.Equals(input.PcVirtualBalance)
                ) &&
                (
                    DebtAmount == input.DebtAmount ||
                    (DebtAmount != null &&
                    DebtAmount.Equals(input.DebtAmount))
                ) &&
                (
                    PcDebtAmount == input.PcDebtAmount ||
                    (PcDebtAmount != null &&
                    PcDebtAmount.Equals(input.PcDebtAmount))
                ) &&
                (
                    CurrentBalanceDate == input.CurrentBalanceDate ||
					CurrentBalanceDate.Equals(input.CurrentBalanceDate)
                ) &&
                (
                    Notes == input.Notes ||
                    (Notes != null &&
                    Notes.Equals(input.Notes))
                ) &&
                (
                    MonthlyPaymentDate == input.MonthlyPaymentDate ||
                    (MonthlyPaymentDate != null &&
                    MonthlyPaymentDate.Equals(input.MonthlyPaymentDate))
                ) &&
                (
                    CreditCardTypeProperty == input.CreditCardTypeProperty ||
                    CreditCardTypeProperty.Equals(input.CreditCardTypeProperty)
                ) &&
                (
                    AccountNumber == input.AccountNumber ||
                    (AccountNumber != null &&
                    AccountNumber.Equals(input.AccountNumber))
                ) &&
                (
                    Iban == input.Iban ||
                    (Iban != null &&
                    Iban.Equals(input.Iban))
                ) &&
                (
                    Bic == input.Bic ||
                    (Bic != null &&
                    Bic.Equals(input.Bic))
                ) &&
                (
                    OpeningBalanceDate == input.OpeningBalanceDate ||
                    (OpeningBalanceDate != null &&
                    OpeningBalanceDate.Equals(input.OpeningBalanceDate))
                ) &&
                (
                    LiabilityTypeProperty == input.LiabilityTypeProperty ||
                    LiabilityTypeProperty.Equals(input.LiabilityTypeProperty)
                ) &&
                (
                    LiabilityDirectionProperty == input.LiabilityDirectionProperty ||
                    LiabilityDirectionProperty.Equals(input.LiabilityDirectionProperty)
                ) &&
                (
                    Interest == input.Interest ||
                    (Interest != null &&
                    Interest.Equals(input.Interest))
                ) &&
                (
                    InterestPeriodProperty == input.InterestPeriodProperty ||
                    InterestPeriodProperty.Equals(input.InterestPeriodProperty)
                ) &&
                (
                    IncludeNetWorth == input.IncludeNetWorth ||
                    IncludeNetWorth.Equals(input.IncludeNetWorth)
                ) &&
                (
                    Longitude == input.Longitude ||
                    (Longitude != null &&
                    Longitude.Equals(input.Longitude))
                ) &&
                (
                    Latitude == input.Latitude ||
                    (Latitude != null &&
                    Latitude.Equals(input.Latitude))
                ) &&
                (
                    ZoomLevel == input.ZoomLevel ||
                    (ZoomLevel != null &&
                    ZoomLevel.Equals(input.ZoomLevel))
                ) &&
                (
                    LastActivity == input.LastActivity ||
                    (LastActivity != null &&
                    LastActivity.Equals(input.LastActivity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
				hashCode = (hashCode * 59) + CreatedAt.GetHashCode();
				hashCode = (hashCode * 59) + UpdatedAt.GetHashCode();
                hashCode = (hashCode * 59) + Active.GetHashCode();
                if (Order != null)
                {
                    hashCode = (hashCode * 59) + Order.GetHashCode();
                }
				hashCode = (hashCode * 59) + Name.GetHashCode();
                hashCode = (hashCode * 59) + Type.GetHashCode();
                hashCode = (hashCode * 59) + AccountRole.GetHashCode();
                if (ObjectGroupId != null)
                {
                    hashCode = (hashCode * 59) + ObjectGroupId.GetHashCode();
                }
                if (ObjectGroupOrder != null)
                {
                    hashCode = (hashCode * 59) + ObjectGroupOrder.GetHashCode();
                }
                if (ObjectGroupTitle != null)
                {
                    hashCode = (hashCode * 59) + ObjectGroupTitle.GetHashCode();
                }
                hashCode = (hashCode * 59) + ObjectHasCurrencySetting.GetHashCode();
				hashCode = (hashCode * 59) + CurrencyId.GetHashCode();
				hashCode = (hashCode * 59) + CurrencyName.GetHashCode();
				hashCode = (hashCode * 59) + CurrencyCode.GetHashCode();
				hashCode = (hashCode * 59) + CurrencySymbol.GetHashCode();
                hashCode = (hashCode * 59) + CurrencyDecimalPlaces.GetHashCode();
                if (PrimaryCurrencyId != null)
                {
                    hashCode = (hashCode * 59) + PrimaryCurrencyId.GetHashCode();
                }
                if (PrimaryCurrencyName != null)
                {
                    hashCode = (hashCode * 59) + PrimaryCurrencyName.GetHashCode();
                }
                if (PrimaryCurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + PrimaryCurrencyCode.GetHashCode();
                }
                if (PrimaryCurrencySymbol != null)
                {
                    hashCode = (hashCode * 59) + PrimaryCurrencySymbol.GetHashCode();
                }
                hashCode = (hashCode * 59) + PrimaryCurrencyDecimalPlaces.GetHashCode();
				hashCode = (hashCode * 59) + CurrentBalance.GetHashCode();
                if (PcCurrentBalance != null)
                {
                    hashCode = (hashCode * 59) + PcCurrentBalance.GetHashCode();
                }
                if (BalanceDifference != null)
                {
                    hashCode = (hashCode * 59) + BalanceDifference.GetHashCode();
                }
                if (PcBalanceDifference != null)
                {
                    hashCode = (hashCode * 59) + PcBalanceDifference.GetHashCode();
                }
				hashCode = (hashCode * 59) + OpeningBalance.GetHashCode();
				hashCode = (hashCode * 59) + PcOpeningBalance.GetHashCode();
				hashCode = (hashCode * 59) + VirtualBalance.GetHashCode();
				hashCode = (hashCode * 59) + PcVirtualBalance.GetHashCode();
                if (DebtAmount != null)
                {
                    hashCode = (hashCode * 59) + DebtAmount.GetHashCode();
                }
                if (PcDebtAmount != null)
                {
                    hashCode = (hashCode * 59) + PcDebtAmount.GetHashCode();
                }
				hashCode = (hashCode * 59) + CurrentBalanceDate.GetHashCode();
                if (Notes != null)
                {
                    hashCode = (hashCode * 59) + Notes.GetHashCode();
                }
                if (MonthlyPaymentDate != null)
                {
                    hashCode = (hashCode * 59) + MonthlyPaymentDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + CreditCardTypeProperty.GetHashCode();
                if (AccountNumber != null)
                {
                    hashCode = (hashCode * 59) + AccountNumber.GetHashCode();
                }
                if (Iban != null)
                {
                    hashCode = (hashCode * 59) + Iban.GetHashCode();
                }
                if (Bic != null)
                {
                    hashCode = (hashCode * 59) + Bic.GetHashCode();
                }
                if (OpeningBalanceDate != null)
                {
                    hashCode = (hashCode * 59) + OpeningBalanceDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + LiabilityTypeProperty.GetHashCode();
                hashCode = (hashCode * 59) + LiabilityDirectionProperty.GetHashCode();
                if (Interest != null)
                {
                    hashCode = (hashCode * 59) + Interest.GetHashCode();
                }
                hashCode = (hashCode * 59) + InterestPeriodProperty.GetHashCode();
                hashCode = (hashCode * 59) + IncludeNetWorth.GetHashCode();
                if (Longitude != null)
                {
                    hashCode = (hashCode * 59) + Longitude.GetHashCode();
                }
                if (Latitude != null)
                {
                    hashCode = (hashCode * 59) + Latitude.GetHashCode();
                }
                if (ZoomLevel != null)
                {
                    hashCode = (hashCode * 59) + ZoomLevel.GetHashCode();
                }
                if (LastActivity != null)
                {
                    hashCode = (hashCode * 59) + LastActivity.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
