/*
 * Firefly III API v6.4.4
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-11-01 @ 20:51:03 (Europe/Amsterdam) 
 *
 * The version of the OpenAPI document: 6.4.4
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// AutocompleteRule
    /// </summary>
    [DataContract(Name = "AutocompleteRule")]
    public partial class AutocompleteRule : IEquatable<AutocompleteRule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AutocompleteRule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AutocompleteRule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AutocompleteRule" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">Name of the rule found by an auto-complete search. (required).</param>
        /// <param name="description">Description of the rule found by auto-complete..</param>
        /// <param name="active">Is the bill active or not?.</param>
        public AutocompleteRule(string id = default(string), string name = default(string), string description = default(string), bool active = default(bool))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for AutocompleteRule and cannot be null");
            }
            Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AutocompleteRule and cannot be null");
            }
            Name = name;
            Description = description;
            Active = active;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>2</example>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Name of the rule found by an auto-complete search.
        /// </summary>
        /// <value>Name of the rule found by an auto-complete search.</value>
        /// <example>Rule one</example>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Description of the rule found by auto-complete.
        /// </summary>
        /// <value>Description of the rule found by auto-complete.</value>
        /// <example>Useful rule.</example>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Is the bill active or not?
        /// </summary>
        /// <value>Is the bill active or not?</value>
        /// <example>true</example>
        [DataMember(Name = "active", EmitDefaultValue = true)]
        [JsonPropertyName("active")]
        public bool Active { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AutocompleteRule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, FireflyIIINet.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as AutocompleteRule);
        }

        /// <summary>
        /// Returns true if AutocompleteRule instances are equal
        /// </summary>
        /// <param name="input">Instance of AutocompleteRule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AutocompleteRule input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    Id == input.Id ||
					Id.Equals(input.Id)
                ) && 
                (
                    Name == input.Name ||
					Name.Equals(input.Name)
                ) && 
                (
                    Description == input.Description ||
					Description.Equals(input.Description)
                ) &&
                (
                    Active == input.Active ||
                    Active.Equals(input.Active)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
				hashCode = (hashCode * 59) + Id.GetHashCode();
				hashCode = (hashCode * 59) + Name.GetHashCode();
				hashCode = (hashCode * 59) + Description.GetHashCode();
                hashCode = (hashCode * 59) + Active.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
