/*
 * Firefly III API v6.2.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-02-05T04:52:02+00:00 
 *
 * The version of the OpenAPI document: 6.2.2
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// Category
    /// </summary>
    [DataContract(Name = "Category")]
    public partial class Category : IEquatable<Category>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Category" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Category() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Category" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="notes">notes.</param>
        public Category(string name = default(string), string notes = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Category and cannot be null");
            }
            Name = name;
            Notes = notes;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        [JsonPropertyName("created_at")]
        [JsonInclude]
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Returns false as CreatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = true)]
        [JsonPropertyName("updated_at")]
        [JsonInclude]
        public DateTime UpdatedAt { get; private set; }

        /// <summary>
        /// Returns false as UpdatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>Lunch</example>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        /// <example>Some example notes</example>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        [JsonPropertyName("notes")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Notes { get; set; }

        /// <summary>
        /// The administration&#39;s native currency ID.
        /// </summary>
        /// <value>The administration&#39;s native currency ID.</value>
        /// <example>5</example>
        [DataMember(Name = "native_currency_id", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_id")]
        [JsonInclude]
        public string NativeCurrencyId { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencyId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencyId()
        {
            return false;
        }
        /// <summary>
        /// The administration&#39;s native currency code.
        /// </summary>
        /// <value>The administration&#39;s native currency code.</value>
        /// <example>EUR</example>
        [DataMember(Name = "native_currency_code", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_code")]
        [JsonInclude]
        public string NativeCurrencyCode { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencyCode should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencyCode()
        {
            return false;
        }
        /// <summary>
        /// The administration&#39;s native currency symbol.
        /// </summary>
        /// <value>The administration&#39;s native currency symbol.</value>
        /// <example>$</example>
        [DataMember(Name = "native_currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_symbol")]
        [JsonInclude]
        public string NativeCurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// The administration&#39;s native currency decimal places.
        /// </summary>
        /// <value>The administration&#39;s native currency decimal places.</value>
        /// <example>2</example>
        [DataMember(Name = "native_currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_decimal_places")]
        [JsonInclude]
        public int NativeCurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Spent
        /// </summary>
        [DataMember(Name = "spent", EmitDefaultValue = true)]
        [JsonPropertyName("spent")]
        [JsonInclude]
        public List<CategorySpent> Spent { get; private set; }

        /// <summary>
        /// Returns false as Spent should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSpent()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Earned
        /// </summary>
        [DataMember(Name = "earned", EmitDefaultValue = true)]
        [JsonPropertyName("earned")]
        [JsonInclude]
        public List<CategoryEarned> Earned { get; private set; }

        /// <summary>
        /// Returns false as Earned should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEarned()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Category {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  NativeCurrencyId: ").Append(NativeCurrencyId).Append("\n");
            sb.Append("  NativeCurrencyCode: ").Append(NativeCurrencyCode).Append("\n");
            sb.Append("  NativeCurrencySymbol: ").Append(NativeCurrencySymbol).Append("\n");
            sb.Append("  NativeCurrencyDecimalPlaces: ").Append(NativeCurrencyDecimalPlaces).Append("\n");
            sb.Append("  Spent: ").Append(Spent).Append("\n");
            sb.Append("  Earned: ").Append(Earned).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, FireflyIIINet.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as Category);
        }

        /// <summary>
        /// Returns true if Category instances are equal
        /// </summary>
        /// <param name="input">Instance of Category to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Category input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    CreatedAt == input.CreatedAt ||
					CreatedAt.Equals(input.CreatedAt)
                ) && 
                (
                    UpdatedAt == input.UpdatedAt ||
					UpdatedAt.Equals(input.UpdatedAt)
                ) && 
                (
                    Name == input.Name ||
					Name.Equals(input.Name)
                ) && 
                (
                    Notes == input.Notes ||
                    (Notes != null &&
                    Notes.Equals(input.Notes))
                ) && 
                (
                    NativeCurrencyId == input.NativeCurrencyId ||
                    (NativeCurrencyId != null &&
                    NativeCurrencyId.Equals(input.NativeCurrencyId))
                ) && 
                (
                    NativeCurrencyCode == input.NativeCurrencyCode ||
                    (NativeCurrencyCode != null &&
                    NativeCurrencyCode.Equals(input.NativeCurrencyCode))
                ) && 
                (
                    NativeCurrencySymbol == input.NativeCurrencySymbol ||
                    (NativeCurrencySymbol != null &&
                    NativeCurrencySymbol.Equals(input.NativeCurrencySymbol))
                ) && 
                (
                    NativeCurrencyDecimalPlaces == input.NativeCurrencyDecimalPlaces ||
                    NativeCurrencyDecimalPlaces.Equals(input.NativeCurrencyDecimalPlaces)
                ) && 
                (
                    Spent == input.Spent ||
                    Spent != null &&
                    input.Spent != null &&
                    Spent.SequenceEqual(input.Spent)
                ) && 
                (
                    Earned == input.Earned ||
                    Earned != null &&
                    input.Earned != null &&
                    Earned.SequenceEqual(input.Earned)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
				hashCode = (hashCode * 59) + CreatedAt.GetHashCode();
				hashCode = (hashCode * 59) + UpdatedAt.GetHashCode();
				hashCode = (hashCode * 59) + Name.GetHashCode();
                if (Notes != null)
                {
                    hashCode = (hashCode * 59) + Notes.GetHashCode();
                }
                if (NativeCurrencyId != null)
                {
                    hashCode = (hashCode * 59) + NativeCurrencyId.GetHashCode();
                }
                if (NativeCurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + NativeCurrencyCode.GetHashCode();
                }
                if (NativeCurrencySymbol != null)
                {
                    hashCode = (hashCode * 59) + NativeCurrencySymbol.GetHashCode();
                }
                hashCode = (hashCode * 59) + NativeCurrencyDecimalPlaces.GetHashCode();
				hashCode = (hashCode * 59) + Spent.GetHashCode();
				hashCode = (hashCode * 59) + Earned.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
