/*
 * Firefly III API v6.4.3
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-10-31 @ 07:30:16 (Europe/Amsterdam) 
 *
 * The version of the OpenAPI document: 6.4.3
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// Defines TransactionTypeProperty
    /// </summary>
    [JsonConverter(typeof(FireflyIIINet.Client.StringEnumMemberConverter))]
    public enum TransactionTypeProperty
    {
        /// <summary>
        /// Enum Withdrawal for value: withdrawal
        /// </summary>
        [EnumMember(Value = "withdrawal")]
        Withdrawal = 1,

        /// <summary>
        /// Enum Deposit for value: deposit
        /// </summary>
        [EnumMember(Value = "deposit")]
        Deposit = 2,

        /// <summary>
        /// Enum Transfer for value: transfer
        /// </summary>
        [EnumMember(Value = "transfer")]
        Transfer = 3,

        /// <summary>
        /// Enum Reconciliation for value: reconciliation
        /// </summary>
        [EnumMember(Value = "reconciliation")]
        Reconciliation = 4,

        /// <summary>
        /// Enum OpeningBalance for value: opening balance
        /// </summary>
        [EnumMember(Value = "opening balance")]
        OpeningBalance = 5
    }

}
