/*
 * Firefly III API v2.0.14
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2024-04-20T05:28:29+00:00
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// TransactionV2Split
    /// </summary>
    [DataContract(Name = "TransactionV2Split")]
    public partial class TransactionV2Split : IEquatable<TransactionV2Split>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("type")]
        public TransactionTypeProperty Type { get; set; }

        /// <summary>
        /// Gets or Sets SourceType
        /// </summary>
        [DataMember(Name = "source_type", EmitDefaultValue = true)]
        [JsonPropertyName("source_type")]
        public AccountTypeProperty? SourceType { get; set; }

        /// <summary>
        /// Gets or Sets DestinationType
        /// </summary>
        [DataMember(Name = "destination_type", EmitDefaultValue = true)]
        [JsonPropertyName("destination_type")]
        public AccountTypeProperty? DestinationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionV2Split" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionV2Split() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionV2Split" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="date">Date of the transaction (required).</param>
        /// <param name="order">Order of this entry in the list of transactions..</param>
        /// <param name="amount">Amount of the transaction. (required).</param>
        /// <param name="nativeAmount">Amount of the transaction in the user&#39;s native currency..</param>
        /// <param name="foreignAmount">The amount in a foreign currency..</param>
        /// <param name="nativeForeignAmount">The amount in a foreign currency, in the user&#39;s native currency.</param>
        /// <param name="currencyId">Currency ID. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_code..</param>
        /// <param name="currencyCode">Currency code. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_id..</param>
        /// <param name="nativeCurrencyId">Currency ID of the user&#39;s native currency..</param>
        /// <param name="nativeCurrencyCode">Currency code of the user&#39;s native currency..</param>
        /// <param name="foreignCurrencyId">Currency ID of the foreign currency. Default is null. Is required when you submit a foreign amount..</param>
        /// <param name="foreignCurrencyCode">Currency code of the foreign currency. Default is NULL. Can be used instead of the foreign_currency_id, but this or the ID is required when submitting a foreign amount..</param>
        /// <param name="description">Description of the transaction. (required).</param>
        /// <param name="sourceId">ID of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account. (required).</param>
        /// <param name="sourceName">Name of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account. Can be used instead of the source_id. If the transaction is a deposit, the source_name can be filled in freely: the account will be created based on the name..</param>
        /// <param name="sourceType">sourceType.</param>
        /// <param name="destinationId">ID of the destination account. For a deposit or a transfer, this must always be an asset account. For withdrawals this must be an expense account. (required).</param>
        /// <param name="destinationName">Name of the destination account. You can submit the name instead of the ID. For everything except transfers, the account will be auto-generated if unknown, so submitting a name is enough..</param>
        /// <param name="destinationType">destinationType.</param>
        /// <param name="budgetId">The budget ID for this transaction..</param>
        /// <param name="categoryId">The category ID for this transaction..</param>
        /// <param name="categoryName">The name of the category to be used. If the category is unknown, it will be created. If the ID and the name point to different categories, the ID overrules the name..</param>
        /// <param name="billId">Optional. Use either this or the bill_name.</param>
        /// <param name="billName">Optional. Use either this or the bill_id.</param>
        /// <param name="reconciled">If the transaction has been reconciled already. When you set this, the amount can no longer be edited by the user..</param>
        /// <param name="notes">notes.</param>
        /// <param name="tags">Array of tags..</param>
        /// <param name="internalReference">Reference to internal reference of other systems..</param>
        /// <param name="externalId">Reference to external ID in other systems..</param>
        /// <param name="externalUrl">External, custom URL for this transaction..</param>
        /// <param name="sepaCc">SEPA Clearing Code.</param>
        /// <param name="sepaCtOp">SEPA Opposing Account Identifier.</param>
        /// <param name="sepaCtId">SEPA end-to-end Identifier.</param>
        /// <param name="sepaDb">SEPA mandate identifier.</param>
        /// <param name="sepaCountry">SEPA Country.</param>
        /// <param name="sepaEp">SEPA External Purpose indicator.</param>
        /// <param name="sepaCi">SEPA Creditor Identifier.</param>
        /// <param name="sepaBatchId">SEPA Batch ID.</param>
        /// <param name="interestDate">interestDate.</param>
        /// <param name="bookDate">bookDate.</param>
        /// <param name="processDate">processDate.</param>
        /// <param name="dueDate">dueDate.</param>
        /// <param name="paymentDate">paymentDate.</param>
        /// <param name="invoiceDate">invoiceDate.</param>
        public TransactionV2Split(TransactionTypeProperty type = default(TransactionTypeProperty), DateTime? date = default(DateTime?), int? order = default(int?), string amount = default(string), string nativeAmount = default(string), string foreignAmount = default(string), string nativeForeignAmount = default(string), string currencyId = default(string), string currencyCode = default(string), string nativeCurrencyId = default(string), string nativeCurrencyCode = default(string), string foreignCurrencyId = default(string), string foreignCurrencyCode = default(string), string description = default(string), string sourceId = default(string), string sourceName = default(string), AccountTypeProperty? sourceType = default(AccountTypeProperty?), string destinationId = default(string), string destinationName = default(string), AccountTypeProperty? destinationType = default(AccountTypeProperty?), string budgetId = default(string), string categoryId = default(string), string categoryName = default(string), string billId = default(string), string billName = default(string), bool reconciled = default(bool), string notes = default(string), List<string> tags = default(List<string>), string internalReference = default(string), string externalId = default(string), string externalUrl = default(string), string sepaCc = default(string), string sepaCtOp = default(string), string sepaCtId = default(string), string sepaDb = default(string), string sepaCountry = default(string), string sepaEp = default(string), string sepaCi = default(string), string sepaBatchId = default(string), DateTime? interestDate = default(DateTime?), DateTime? bookDate = default(DateTime?), DateTime? processDate = default(DateTime?), DateTime? dueDate = default(DateTime?), DateTime? paymentDate = default(DateTime?), DateTime? invoiceDate = default(DateTime?))
        {
            Type = type;
            Date = date ?? default(DateTime);
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for TransactionV2Split and cannot be null");
            }
            Amount = amount;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for TransactionV2Split and cannot be null");
            }
            Description = description;
            // to ensure "sourceId" is required (not null)
            if (sourceId == null)
            {
                throw new ArgumentNullException("sourceId is a required property for TransactionV2Split and cannot be null");
            }
            SourceId = sourceId;
            // to ensure "destinationId" is required (not null)
            if (destinationId == null)
            {
                throw new ArgumentNullException("destinationId is a required property for TransactionV2Split and cannot be null");
            }
            DestinationId = destinationId;
            Order = order;
            NativeAmount = nativeAmount;
            ForeignAmount = foreignAmount;
            NativeForeignAmount = nativeForeignAmount;
            CurrencyId = currencyId;
            CurrencyCode = currencyCode;
            NativeCurrencyId = nativeCurrencyId;
            NativeCurrencyCode = nativeCurrencyCode;
            ForeignCurrencyId = foreignCurrencyId;
            ForeignCurrencyCode = foreignCurrencyCode;
            SourceName = sourceName;
            SourceType = sourceType;
            DestinationName = destinationName;
            DestinationType = destinationType;
            BudgetId = budgetId;
            CategoryId = categoryId;
            CategoryName = categoryName;
            BillId = billId;
            BillName = billName;
            Reconciled = reconciled;
            Notes = notes;
            Tags = tags;
            InternalReference = internalReference;
            ExternalId = externalId;
            ExternalUrl = externalUrl;
            SepaCc = sepaCc;
            SepaCtOp = sepaCtOp;
            SepaCtId = sepaCtId;
            SepaDb = sepaDb;
            SepaCountry = sepaCountry;
            SepaEp = sepaEp;
            SepaCi = sepaCi;
            SepaBatchId = sepaBatchId;
            InterestDate = interestDate;
            BookDate = bookDate;
            ProcessDate = processDate;
            DueDate = dueDate;
            PaymentDate = paymentDate;
            InvoiceDate = invoiceDate;
        }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        /// <example>3</example>
        [DataMember(Name = "user", EmitDefaultValue = true)]
        [JsonPropertyName("user")]
        [JsonInclude]
        public string User { get; private set; }

        /// <summary>
        /// Returns false as User should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUser()
        {
            return false;
        }
        /// <summary>
        /// User group ID
        /// </summary>
        /// <value>User group ID</value>
        /// <example>3</example>
        [DataMember(Name = "user_group", EmitDefaultValue = true)]
        [JsonPropertyName("user_group")]
        [JsonInclude]
        public string UserGroup { get; private set; }

        /// <summary>
        /// Returns false as UserGroup should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUserGroup()
        {
            return false;
        }
        /// <summary>
        /// ID of the underlying transaction journal. Each transaction consists of a transaction group (see the top ID) and one or more journals making up the splits of the transaction.
        /// </summary>
        /// <value>ID of the underlying transaction journal. Each transaction consists of a transaction group (see the top ID) and one or more journals making up the splits of the transaction. </value>
        /// <example>10421</example>
        [DataMember(Name = "transaction_journal_id", EmitDefaultValue = true)]
        [JsonPropertyName("transaction_journal_id")]
        [JsonInclude]
        public string TransactionJournalId { get; private set; }

        /// <summary>
        /// Returns false as TransactionJournalId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTransactionJournalId()
        {
            return false;
        }
        /// <summary>
        /// Date of the transaction
        /// </summary>
        /// <value>Date of the transaction</value>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "date", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// Order of this entry in the list of transactions.
        /// </summary>
        /// <value>Order of this entry in the list of transactions.</value>
        /// <example>0</example>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        [JsonPropertyName("order")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? Order { get; set; }

        /// <summary>
        /// Amount of the transaction.
        /// </summary>
        /// <value>Amount of the transaction.</value>
        /// <example>123.45</example>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Amount of the transaction in the user&#39;s native currency.
        /// </summary>
        /// <value>Amount of the transaction in the user&#39;s native currency.</value>
        /// <example>123.45</example>
        [DataMember(Name = "native_amount", EmitDefaultValue = false)]
        [JsonPropertyName("native_amount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string NativeAmount { get; set; }

        /// <summary>
        /// The amount in a foreign currency.
        /// </summary>
        /// <value>The amount in a foreign currency.</value>
        /// <example>123.45</example>
        [DataMember(Name = "foreign_amount", EmitDefaultValue = false)]
        [JsonPropertyName("foreign_amount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ForeignAmount { get; set; }

        /// <summary>
        /// The amount in a foreign currency, in the user&#39;s native currency
        /// </summary>
        /// <value>The amount in a foreign currency, in the user&#39;s native currency</value>
        /// <example>123.45</example>
        [DataMember(Name = "native_foreign_amount", EmitDefaultValue = false)]
        [JsonPropertyName("native_foreign_amount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string NativeForeignAmount { get; set; }

        /// <summary>
        /// Currency ID. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_code.
        /// </summary>
        /// <value>Currency ID. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_code.</value>
        /// <example>12</example>
        [DataMember(Name = "currency_id", EmitDefaultValue = false)]
        [JsonPropertyName("currency_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string CurrencyId { get; set; }

        /// <summary>
        /// Currency code. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_id.
        /// </summary>
        /// <value>Currency code. Default is the source account&#39;s currency, or the user&#39;s default currency. Can be used instead of currency_id.</value>
        /// <example>EUR</example>
        [DataMember(Name = "currency_code", EmitDefaultValue = false)]
        [JsonPropertyName("currency_code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets CurrencySymbol
        /// </summary>
        /// <example>$</example>
        [DataMember(Name = "currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("currency_symbol")]
        [JsonInclude]
        public string CurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as CurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets CurrencyName
        /// </summary>
        /// <example>Euro</example>
        [DataMember(Name = "currency_name", EmitDefaultValue = true)]
        [JsonPropertyName("currency_name")]
        [JsonInclude]
        public string CurrencyName { get; private set; }

        /// <summary>
        /// Returns false as CurrencyName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrencyName()
        {
            return false;
        }
        /// <summary>
        /// Number of decimals used in this currency.
        /// </summary>
        /// <value>Number of decimals used in this currency.</value>
        /// <example>2</example>
        [DataMember(Name = "currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("currency_decimal_places")]
        [JsonInclude]
        public int CurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as CurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// Currency ID of the user&#39;s native currency.
        /// </summary>
        /// <value>Currency ID of the user&#39;s native currency.</value>
        /// <example>12</example>
        [DataMember(Name = "native_currency_id", EmitDefaultValue = false)]
        [JsonPropertyName("native_currency_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string NativeCurrencyId { get; set; }

        /// <summary>
        /// Currency code of the user&#39;s native currency.
        /// </summary>
        /// <value>Currency code of the user&#39;s native currency.</value>
        /// <example>EUR</example>
        [DataMember(Name = "native_currency_code", EmitDefaultValue = false)]
        [JsonPropertyName("native_currency_code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string NativeCurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets NativeCurrencySymbol
        /// </summary>
        /// <example>$</example>
        [DataMember(Name = "native_currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_symbol")]
        [JsonInclude]
        public string NativeCurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets NativeCurrencyName
        /// </summary>
        /// <example>Euro</example>
        [DataMember(Name = "native_currency_name", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_name")]
        [JsonInclude]
        public string NativeCurrencyName { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencyName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencyName()
        {
            return false;
        }
        /// <summary>
        /// Number of decimals used in this currency.
        /// </summary>
        /// <value>Number of decimals used in this currency.</value>
        /// <example>2</example>
        [DataMember(Name = "native_currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("native_currency_decimal_places")]
        [JsonInclude]
        public int NativeCurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as NativeCurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNativeCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// Currency ID of the foreign currency. Default is null. Is required when you submit a foreign amount.
        /// </summary>
        /// <value>Currency ID of the foreign currency. Default is null. Is required when you submit a foreign amount.</value>
        /// <example>17</example>
        [DataMember(Name = "foreign_currency_id", EmitDefaultValue = false)]
        [JsonPropertyName("foreign_currency_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ForeignCurrencyId { get; set; }

        /// <summary>
        /// Currency code of the foreign currency. Default is NULL. Can be used instead of the foreign_currency_id, but this or the ID is required when submitting a foreign amount.
        /// </summary>
        /// <value>Currency code of the foreign currency. Default is NULL. Can be used instead of the foreign_currency_id, but this or the ID is required when submitting a foreign amount.</value>
        /// <example>USD</example>
        [DataMember(Name = "foreign_currency_code", EmitDefaultValue = false)]
        [JsonPropertyName("foreign_currency_code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ForeignCurrencyCode { get; set; }

        /// <summary>
        /// Gets or Sets ForeignCurrencySymbol
        /// </summary>
        /// <example>$</example>
        [DataMember(Name = "foreign_currency_symbol", EmitDefaultValue = false)]
        [JsonPropertyName("foreign_currency_symbol")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string ForeignCurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as ForeignCurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeForeignCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// Number of decimals in the currency
        /// </summary>
        /// <value>Number of decimals in the currency</value>
        /// <example>2</example>
        [DataMember(Name = "foreign_currency_decimal_places", EmitDefaultValue = false)]
        [JsonPropertyName("foreign_currency_decimal_places")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public int? ForeignCurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as ForeignCurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeForeignCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// Description of the transaction.
        /// </summary>
        /// <value>Description of the transaction.</value>
        /// <example>Vegetables</example>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// ID of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account.
        /// </summary>
        /// <value>ID of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account.</value>
        /// <example>2</example>
        [DataMember(Name = "source_id", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("source_id")]
        public string SourceId { get; set; }

        /// <summary>
        /// Name of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account. Can be used instead of the source_id. If the transaction is a deposit, the source_name can be filled in freely: the account will be created based on the name.
        /// </summary>
        /// <value>Name of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account. Can be used instead of the source_id. If the transaction is a deposit, the source_name can be filled in freely: the account will be created based on the name.</value>
        /// <example>Checking account</example>
        [DataMember(Name = "source_name", EmitDefaultValue = false)]
        [JsonPropertyName("source_name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SourceName { get; set; }

        /// <summary>
        /// Gets or Sets SourceIban
        /// </summary>
        /// <example>NL02ABNA0123456789</example>
        [DataMember(Name = "source_iban", EmitDefaultValue = false)]
        [JsonPropertyName("source_iban")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string SourceIban { get; private set; }

        /// <summary>
        /// Returns false as SourceIban should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSourceIban()
        {
            return false;
        }
        /// <summary>
        /// ID of the destination account. For a deposit or a transfer, this must always be an asset account. For withdrawals this must be an expense account.
        /// </summary>
        /// <value>ID of the destination account. For a deposit or a transfer, this must always be an asset account. For withdrawals this must be an expense account.</value>
        /// <example>2</example>
        [DataMember(Name = "destination_id", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("destination_id")]
        public string DestinationId { get; set; }

        /// <summary>
        /// Name of the destination account. You can submit the name instead of the ID. For everything except transfers, the account will be auto-generated if unknown, so submitting a name is enough.
        /// </summary>
        /// <value>Name of the destination account. You can submit the name instead of the ID. For everything except transfers, the account will be auto-generated if unknown, so submitting a name is enough.</value>
        /// <example>Buy and Large</example>
        [DataMember(Name = "destination_name", EmitDefaultValue = false)]
        [JsonPropertyName("destination_name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string DestinationName { get; set; }

        /// <summary>
        /// Gets or Sets DestinationIban
        /// </summary>
        /// <example>NL02ABNA0123456789</example>
        [DataMember(Name = "destination_iban", EmitDefaultValue = false)]
        [JsonPropertyName("destination_iban")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string DestinationIban { get; private set; }

        /// <summary>
        /// Returns false as DestinationIban should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDestinationIban()
        {
            return false;
        }
        /// <summary>
        /// The budget ID for this transaction.
        /// </summary>
        /// <value>The budget ID for this transaction.</value>
        /// <example>4</example>
        [DataMember(Name = "budget_id", EmitDefaultValue = false)]
        [JsonPropertyName("budget_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string BudgetId { get; set; }

        /// <summary>
        /// The name of the budget to be used. If the budget name is unknown, the ID will be used or the value will be ignored.
        /// </summary>
        /// <value>The name of the budget to be used. If the budget name is unknown, the ID will be used or the value will be ignored.</value>
        /// <example>Groceries</example>
        [DataMember(Name = "budget_name", EmitDefaultValue = false)]
        [JsonPropertyName("budget_name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string BudgetName { get; private set; }

        /// <summary>
        /// Returns false as BudgetName should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBudgetName()
        {
            return false;
        }
        /// <summary>
        /// The category ID for this transaction.
        /// </summary>
        /// <value>The category ID for this transaction.</value>
        /// <example>43</example>
        [DataMember(Name = "category_id", EmitDefaultValue = false)]
        [JsonPropertyName("category_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string CategoryId { get; set; }

        /// <summary>
        /// The name of the category to be used. If the category is unknown, it will be created. If the ID and the name point to different categories, the ID overrules the name.
        /// </summary>
        /// <value>The name of the category to be used. If the category is unknown, it will be created. If the ID and the name point to different categories, the ID overrules the name.</value>
        /// <example>Groceries</example>
        [DataMember(Name = "category_name", EmitDefaultValue = false)]
        [JsonPropertyName("category_name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string CategoryName { get; set; }

        /// <summary>
        /// Optional. Use either this or the bill_name
        /// </summary>
        /// <value>Optional. Use either this or the bill_name</value>
        /// <example>111</example>
        [DataMember(Name = "bill_id", EmitDefaultValue = false)]
        [JsonPropertyName("bill_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string BillId { get; set; }

        /// <summary>
        /// Optional. Use either this or the bill_id
        /// </summary>
        /// <value>Optional. Use either this or the bill_id</value>
        /// <example>Monthly rent</example>
        [DataMember(Name = "bill_name", EmitDefaultValue = false)]
        [JsonPropertyName("bill_name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string BillName { get; set; }

        /// <summary>
        /// If the transaction has been reconciled already. When you set this, the amount can no longer be edited by the user.
        /// </summary>
        /// <value>If the transaction has been reconciled already. When you set this, the amount can no longer be edited by the user.</value>
        /// <example>false</example>
        [DataMember(Name = "reconciled", EmitDefaultValue = true)]
        [JsonPropertyName("reconciled")]
        public bool Reconciled { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        /// <example>Some example notes</example>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        [JsonPropertyName("notes")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Notes { get; set; }

        /// <summary>
        /// Array of tags.
        /// </summary>
        /// <value>Array of tags.</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        [JsonPropertyName("tags")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Reference to internal reference of other systems.
        /// </summary>
        /// <value>Reference to internal reference of other systems.</value>
        [DataMember(Name = "internal_reference", EmitDefaultValue = false)]
        [JsonPropertyName("internal_reference")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string InternalReference { get; set; }

        /// <summary>
        /// Reference to external ID in other systems.
        /// </summary>
        /// <value>Reference to external ID in other systems.</value>
        [DataMember(Name = "external_id", EmitDefaultValue = false)]
        [JsonPropertyName("external_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ExternalId { get; set; }

        /// <summary>
        /// External, custom URL for this transaction.
        /// </summary>
        /// <value>External, custom URL for this transaction.</value>
        [DataMember(Name = "external_url", EmitDefaultValue = false)]
        [JsonPropertyName("external_url")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string ExternalUrl { get; set; }

        /// <summary>
        /// System generated identifier for original creator of transaction.
        /// </summary>
        /// <value>System generated identifier for original creator of transaction.</value>
        [DataMember(Name = "original_source", EmitDefaultValue = false)]
        [JsonPropertyName("original_source")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string OriginalSource { get; private set; }

        /// <summary>
        /// Returns false as OriginalSource should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOriginalSource()
        {
            return false;
        }
        /// <summary>
        /// Reference to recurrence that made the transaction.
        /// </summary>
        /// <value>Reference to recurrence that made the transaction.</value>
        [DataMember(Name = "recurrence_id", EmitDefaultValue = false)]
        [JsonPropertyName("recurrence_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string RecurrenceId { get; private set; }

        /// <summary>
        /// Returns false as RecurrenceId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRecurrenceId()
        {
            return false;
        }
        /// <summary>
        /// Total number of transactions expected to be created by this recurrence repetition. Will be 0 if infinite.
        /// </summary>
        /// <value>Total number of transactions expected to be created by this recurrence repetition. Will be 0 if infinite.</value>
        /// <example>0</example>
        [DataMember(Name = "recurrence_total", EmitDefaultValue = false)]
        [JsonPropertyName("recurrence_total")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public int? RecurrenceTotal { get; private set; }

        /// <summary>
        /// Returns false as RecurrenceTotal should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRecurrenceTotal()
        {
            return false;
        }
        /// <summary>
        /// The # of the current transaction created under this recurrence.
        /// </summary>
        /// <value>The # of the current transaction created under this recurrence.</value>
        /// <example>12</example>
        [DataMember(Name = "recurrence_count", EmitDefaultValue = false)]
        [JsonPropertyName("recurrence_count")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public int? RecurrenceCount { get; private set; }

        /// <summary>
        /// Returns false as RecurrenceCount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRecurrenceCount()
        {
            return false;
        }
        /// <summary>
        /// Hash value of original import transaction (for duplicate detection).
        /// </summary>
        /// <value>Hash value of original import transaction (for duplicate detection).</value>
        [DataMember(Name = "import_hash_v2", EmitDefaultValue = false)]
        [JsonPropertyName("import_hash_v2")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        [JsonInclude]
        public string ImportHashV2 { get; private set; }

        /// <summary>
        /// Returns false as ImportHashV2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeImportHashV2()
        {
            return false;
        }
        /// <summary>
        /// SEPA Clearing Code
        /// </summary>
        /// <value>SEPA Clearing Code</value>
        [DataMember(Name = "sepa_cc", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_cc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaCc { get; set; }

        /// <summary>
        /// SEPA Opposing Account Identifier
        /// </summary>
        /// <value>SEPA Opposing Account Identifier</value>
        [DataMember(Name = "sepa_ct_op", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_ct_op")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaCtOp { get; set; }

        /// <summary>
        /// SEPA end-to-end Identifier
        /// </summary>
        /// <value>SEPA end-to-end Identifier</value>
        [DataMember(Name = "sepa_ct_id", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_ct_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaCtId { get; set; }

        /// <summary>
        /// SEPA mandate identifier
        /// </summary>
        /// <value>SEPA mandate identifier</value>
        [DataMember(Name = "sepa_db", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_db")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaDb { get; set; }

        /// <summary>
        /// SEPA Country
        /// </summary>
        /// <value>SEPA Country</value>
        [DataMember(Name = "sepa_country", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_country")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaCountry { get; set; }

        /// <summary>
        /// SEPA External Purpose indicator
        /// </summary>
        /// <value>SEPA External Purpose indicator</value>
        [DataMember(Name = "sepa_ep", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_ep")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaEp { get; set; }

        /// <summary>
        /// SEPA Creditor Identifier
        /// </summary>
        /// <value>SEPA Creditor Identifier</value>
        [DataMember(Name = "sepa_ci", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_ci")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaCi { get; set; }

        /// <summary>
        /// SEPA Batch ID
        /// </summary>
        /// <value>SEPA Batch ID</value>
        [DataMember(Name = "sepa_batch_id", EmitDefaultValue = false)]
        [JsonPropertyName("sepa_batch_id")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string SepaBatchId { get; set; }

        /// <summary>
        /// Gets or Sets InterestDate
        /// </summary>
        [DataMember(Name = "interest_date", EmitDefaultValue = false)]
        [JsonPropertyName("interest_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? InterestDate { get; set; }

        /// <summary>
        /// Gets or Sets BookDate
        /// </summary>
        [DataMember(Name = "book_date", EmitDefaultValue = false)]
        [JsonPropertyName("book_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? BookDate { get; set; }

        /// <summary>
        /// Gets or Sets ProcessDate
        /// </summary>
        [DataMember(Name = "process_date", EmitDefaultValue = false)]
        [JsonPropertyName("process_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? ProcessDate { get; set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>
        [DataMember(Name = "due_date", EmitDefaultValue = false)]
        [JsonPropertyName("due_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? DueDate { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDate
        /// </summary>
        [DataMember(Name = "payment_date", EmitDefaultValue = false)]
        [JsonPropertyName("payment_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? PaymentDate { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceDate
        /// </summary>
        [DataMember(Name = "invoice_date", EmitDefaultValue = false)]
        [JsonPropertyName("invoice_date")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime? InvoiceDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionV2Split {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  UserGroup: ").Append(UserGroup).Append("\n");
            sb.Append("  TransactionJournalId: ").Append(TransactionJournalId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  NativeAmount: ").Append(NativeAmount).Append("\n");
            sb.Append("  ForeignAmount: ").Append(ForeignAmount).Append("\n");
            sb.Append("  NativeForeignAmount: ").Append(NativeForeignAmount).Append("\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  CurrencySymbol: ").Append(CurrencySymbol).Append("\n");
            sb.Append("  CurrencyName: ").Append(CurrencyName).Append("\n");
            sb.Append("  CurrencyDecimalPlaces: ").Append(CurrencyDecimalPlaces).Append("\n");
            sb.Append("  NativeCurrencyId: ").Append(NativeCurrencyId).Append("\n");
            sb.Append("  NativeCurrencyCode: ").Append(NativeCurrencyCode).Append("\n");
            sb.Append("  NativeCurrencySymbol: ").Append(NativeCurrencySymbol).Append("\n");
            sb.Append("  NativeCurrencyName: ").Append(NativeCurrencyName).Append("\n");
            sb.Append("  NativeCurrencyDecimalPlaces: ").Append(NativeCurrencyDecimalPlaces).Append("\n");
            sb.Append("  ForeignCurrencyId: ").Append(ForeignCurrencyId).Append("\n");
            sb.Append("  ForeignCurrencyCode: ").Append(ForeignCurrencyCode).Append("\n");
            sb.Append("  ForeignCurrencySymbol: ").Append(ForeignCurrencySymbol).Append("\n");
            sb.Append("  ForeignCurrencyDecimalPlaces: ").Append(ForeignCurrencyDecimalPlaces).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SourceId: ").Append(SourceId).Append("\n");
            sb.Append("  SourceName: ").Append(SourceName).Append("\n");
            sb.Append("  SourceIban: ").Append(SourceIban).Append("\n");
            sb.Append("  SourceType: ").Append(SourceType).Append("\n");
            sb.Append("  DestinationId: ").Append(DestinationId).Append("\n");
            sb.Append("  DestinationName: ").Append(DestinationName).Append("\n");
            sb.Append("  DestinationIban: ").Append(DestinationIban).Append("\n");
            sb.Append("  DestinationType: ").Append(DestinationType).Append("\n");
            sb.Append("  BudgetId: ").Append(BudgetId).Append("\n");
            sb.Append("  BudgetName: ").Append(BudgetName).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  CategoryName: ").Append(CategoryName).Append("\n");
            sb.Append("  BillId: ").Append(BillId).Append("\n");
            sb.Append("  BillName: ").Append(BillName).Append("\n");
            sb.Append("  Reconciled: ").Append(Reconciled).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  InternalReference: ").Append(InternalReference).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  ExternalUrl: ").Append(ExternalUrl).Append("\n");
            sb.Append("  OriginalSource: ").Append(OriginalSource).Append("\n");
            sb.Append("  RecurrenceId: ").Append(RecurrenceId).Append("\n");
            sb.Append("  RecurrenceTotal: ").Append(RecurrenceTotal).Append("\n");
            sb.Append("  RecurrenceCount: ").Append(RecurrenceCount).Append("\n");
            sb.Append("  ImportHashV2: ").Append(ImportHashV2).Append("\n");
            sb.Append("  SepaCc: ").Append(SepaCc).Append("\n");
            sb.Append("  SepaCtOp: ").Append(SepaCtOp).Append("\n");
            sb.Append("  SepaCtId: ").Append(SepaCtId).Append("\n");
            sb.Append("  SepaDb: ").Append(SepaDb).Append("\n");
            sb.Append("  SepaCountry: ").Append(SepaCountry).Append("\n");
            sb.Append("  SepaEp: ").Append(SepaEp).Append("\n");
            sb.Append("  SepaCi: ").Append(SepaCi).Append("\n");
            sb.Append("  SepaBatchId: ").Append(SepaBatchId).Append("\n");
            sb.Append("  InterestDate: ").Append(InterestDate).Append("\n");
            sb.Append("  BookDate: ").Append(BookDate).Append("\n");
            sb.Append("  ProcessDate: ").Append(ProcessDate).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  PaymentDate: ").Append(PaymentDate).Append("\n");
            sb.Append("  InvoiceDate: ").Append(InvoiceDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, FireflyIIINet.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TransactionV2Split);
        }

        /// <summary>
        /// Returns true if TransactionV2Split instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionV2Split to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionV2Split input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    User == input.User ||
					User.Equals(input.User)
                ) &&
                (
                    UserGroup == input.UserGroup ||
					UserGroup.Equals(input.UserGroup)
                ) &&
                (
                    TransactionJournalId == input.TransactionJournalId ||
					TransactionJournalId.Equals(input.TransactionJournalId)
                ) &&
                (
                    Type == input.Type ||
                    Type.Equals(input.Type)
                ) &&
                (
                    Date == input.Date ||
					Date.Equals(input.Date)
                ) &&
                (
                    Order == input.Order ||
                    (Order != null &&
                    Order.Equals(input.Order))
                ) &&
                (
                    Amount == input.Amount ||
					Amount.Equals(input.Amount)
                ) &&
                (
                    NativeAmount == input.NativeAmount ||
                    (NativeAmount != null &&
                    NativeAmount.Equals(input.NativeAmount))
                ) &&
                (
                    ForeignAmount == input.ForeignAmount ||
                    (ForeignAmount != null &&
                    ForeignAmount.Equals(input.ForeignAmount))
                ) &&
                (
                    NativeForeignAmount == input.NativeForeignAmount ||
                    (NativeForeignAmount != null &&
                    NativeForeignAmount.Equals(input.NativeForeignAmount))
                ) &&
                (
                    CurrencyId == input.CurrencyId ||
                    (CurrencyId != null &&
                    CurrencyId.Equals(input.CurrencyId))
                ) &&
                (
                    CurrencyCode == input.CurrencyCode ||
                    (CurrencyCode != null &&
                    CurrencyCode.Equals(input.CurrencyCode))
                ) &&
                (
                    CurrencySymbol == input.CurrencySymbol ||
					CurrencySymbol.Equals(input.CurrencySymbol)
                ) &&
                (
                    CurrencyName == input.CurrencyName ||
					CurrencyName.Equals(input.CurrencyName)
                ) &&
                (
                    CurrencyDecimalPlaces == input.CurrencyDecimalPlaces ||
                    CurrencyDecimalPlaces.Equals(input.CurrencyDecimalPlaces)
                ) &&
                (
                    NativeCurrencyId == input.NativeCurrencyId ||
                    (NativeCurrencyId != null &&
                    NativeCurrencyId.Equals(input.NativeCurrencyId))
                ) &&
                (
                    NativeCurrencyCode == input.NativeCurrencyCode ||
                    (NativeCurrencyCode != null &&
                    NativeCurrencyCode.Equals(input.NativeCurrencyCode))
                ) &&
                (
                    NativeCurrencySymbol == input.NativeCurrencySymbol ||
					NativeCurrencySymbol.Equals(input.NativeCurrencySymbol)
                ) &&
                (
                    NativeCurrencyName == input.NativeCurrencyName ||
					NativeCurrencyName.Equals(input.NativeCurrencyName)
                ) &&
                (
                    NativeCurrencyDecimalPlaces == input.NativeCurrencyDecimalPlaces ||
                    NativeCurrencyDecimalPlaces.Equals(input.NativeCurrencyDecimalPlaces)
                ) &&
                (
                    ForeignCurrencyId == input.ForeignCurrencyId ||
                    (ForeignCurrencyId != null &&
                    ForeignCurrencyId.Equals(input.ForeignCurrencyId))
                ) &&
                (
                    ForeignCurrencyCode == input.ForeignCurrencyCode ||
                    (ForeignCurrencyCode != null &&
                    ForeignCurrencyCode.Equals(input.ForeignCurrencyCode))
                ) &&
                (
                    ForeignCurrencySymbol == input.ForeignCurrencySymbol ||
                    (ForeignCurrencySymbol != null &&
                    ForeignCurrencySymbol.Equals(input.ForeignCurrencySymbol))
                ) &&
                (
                    ForeignCurrencyDecimalPlaces == input.ForeignCurrencyDecimalPlaces ||
                    (ForeignCurrencyDecimalPlaces != null &&
                    ForeignCurrencyDecimalPlaces.Equals(input.ForeignCurrencyDecimalPlaces))
                ) &&
                (
                    Description == input.Description ||
					Description.Equals(input.Description)
                ) &&
                (
                    SourceId == input.SourceId ||
                    (SourceId != null &&
                    SourceId.Equals(input.SourceId))
                ) &&
                (
                    SourceName == input.SourceName ||
                    (SourceName != null &&
                    SourceName.Equals(input.SourceName))
                ) &&
                (
                    SourceIban == input.SourceIban ||
                    (SourceIban != null &&
                    SourceIban.Equals(input.SourceIban))
                ) &&
                (
                    SourceType == input.SourceType ||
                    SourceType.Equals(input.SourceType)
                ) &&
                (
                    DestinationId == input.DestinationId ||
                    (DestinationId != null &&
                    DestinationId.Equals(input.DestinationId))
                ) &&
                (
                    DestinationName == input.DestinationName ||
                    (DestinationName != null &&
                    DestinationName.Equals(input.DestinationName))
                ) &&
                (
                    DestinationIban == input.DestinationIban ||
                    (DestinationIban != null &&
                    DestinationIban.Equals(input.DestinationIban))
                ) &&
                (
                    DestinationType == input.DestinationType ||
                    DestinationType.Equals(input.DestinationType)
                ) &&
                (
                    BudgetId == input.BudgetId ||
                    (BudgetId != null &&
                    BudgetId.Equals(input.BudgetId))
                ) &&
                (
                    BudgetName == input.BudgetName ||
                    (BudgetName != null &&
                    BudgetName.Equals(input.BudgetName))
                ) &&
                (
                    CategoryId == input.CategoryId ||
                    (CategoryId != null &&
                    CategoryId.Equals(input.CategoryId))
                ) &&
                (
                    CategoryName == input.CategoryName ||
                    (CategoryName != null &&
                    CategoryName.Equals(input.CategoryName))
                ) &&
                (
                    BillId == input.BillId ||
                    (BillId != null &&
                    BillId.Equals(input.BillId))
                ) &&
                (
                    BillName == input.BillName ||
                    (BillName != null &&
                    BillName.Equals(input.BillName))
                ) &&
                (
                    Reconciled == input.Reconciled ||
                    Reconciled.Equals(input.Reconciled)
                ) &&
                (
                    Notes == input.Notes ||
                    (Notes != null &&
                    Notes.Equals(input.Notes))
                ) &&
                (
                    Tags == input.Tags ||
                    Tags != null &&
                    input.Tags != null &&
                    Tags.SequenceEqual(input.Tags)
                ) &&
                (
                    InternalReference == input.InternalReference ||
                    (InternalReference != null &&
                    InternalReference.Equals(input.InternalReference))
                ) &&
                (
                    ExternalId == input.ExternalId ||
                    (ExternalId != null &&
                    ExternalId.Equals(input.ExternalId))
                ) &&
                (
                    ExternalUrl == input.ExternalUrl ||
                    (ExternalUrl != null &&
                    ExternalUrl.Equals(input.ExternalUrl))
                ) &&
                (
                    OriginalSource == input.OriginalSource ||
                    (OriginalSource != null &&
                    OriginalSource.Equals(input.OriginalSource))
                ) &&
                (
                    RecurrenceId == input.RecurrenceId ||
                    (RecurrenceId != null &&
                    RecurrenceId.Equals(input.RecurrenceId))
                ) &&
                (
                    RecurrenceTotal == input.RecurrenceTotal ||
                    (RecurrenceTotal != null &&
                    RecurrenceTotal.Equals(input.RecurrenceTotal))
                ) &&
                (
                    RecurrenceCount == input.RecurrenceCount ||
                    (RecurrenceCount != null &&
                    RecurrenceCount.Equals(input.RecurrenceCount))
                ) &&
                (
                    ImportHashV2 == input.ImportHashV2 ||
                    (ImportHashV2 != null &&
                    ImportHashV2.Equals(input.ImportHashV2))
                ) &&
                (
                    SepaCc == input.SepaCc ||
                    (SepaCc != null &&
                    SepaCc.Equals(input.SepaCc))
                ) &&
                (
                    SepaCtOp == input.SepaCtOp ||
                    (SepaCtOp != null &&
                    SepaCtOp.Equals(input.SepaCtOp))
                ) &&
                (
                    SepaCtId == input.SepaCtId ||
                    (SepaCtId != null &&
                    SepaCtId.Equals(input.SepaCtId))
                ) &&
                (
                    SepaDb == input.SepaDb ||
                    (SepaDb != null &&
                    SepaDb.Equals(input.SepaDb))
                ) &&
                (
                    SepaCountry == input.SepaCountry ||
                    (SepaCountry != null &&
                    SepaCountry.Equals(input.SepaCountry))
                ) &&
                (
                    SepaEp == input.SepaEp ||
                    (SepaEp != null &&
                    SepaEp.Equals(input.SepaEp))
                ) &&
                (
                    SepaCi == input.SepaCi ||
                    (SepaCi != null &&
                    SepaCi.Equals(input.SepaCi))
                ) &&
                (
                    SepaBatchId == input.SepaBatchId ||
                    (SepaBatchId != null &&
                    SepaBatchId.Equals(input.SepaBatchId))
                ) &&
                (
                    InterestDate == input.InterestDate ||
                    (InterestDate != null &&
                    InterestDate.Equals(input.InterestDate))
                ) &&
                (
                    BookDate == input.BookDate ||
                    (BookDate != null &&
                    BookDate.Equals(input.BookDate))
                ) &&
                (
                    ProcessDate == input.ProcessDate ||
                    (ProcessDate != null &&
                    ProcessDate.Equals(input.ProcessDate))
                ) &&
                (
                    DueDate == input.DueDate ||
                    (DueDate != null &&
                    DueDate.Equals(input.DueDate))
                ) &&
                (
                    PaymentDate == input.PaymentDate ||
                    (PaymentDate != null &&
                    PaymentDate.Equals(input.PaymentDate))
                ) &&
                (
                    InvoiceDate == input.InvoiceDate ||
                    (InvoiceDate != null &&
                    InvoiceDate.Equals(input.InvoiceDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
				hashCode = (hashCode * 59) + User.GetHashCode();
				hashCode = (hashCode * 59) + UserGroup.GetHashCode();
				hashCode = (hashCode * 59) + TransactionJournalId.GetHashCode();
                hashCode = (hashCode * 59) + Type.GetHashCode();
				hashCode = (hashCode * 59) + Date.GetHashCode();
                if (Order != null)
                {
                    hashCode = (hashCode * 59) + Order.GetHashCode();
                }
				hashCode = (hashCode * 59) + Amount.GetHashCode();
                if (NativeAmount != null)
                {
                    hashCode = (hashCode * 59) + NativeAmount.GetHashCode();
                }
                if (ForeignAmount != null)
                {
                    hashCode = (hashCode * 59) + ForeignAmount.GetHashCode();
                }
                if (NativeForeignAmount != null)
                {
                    hashCode = (hashCode * 59) + NativeForeignAmount.GetHashCode();
                }
                if (CurrencyId != null)
                {
                    hashCode = (hashCode * 59) + CurrencyId.GetHashCode();
                }
                if (CurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + CurrencyCode.GetHashCode();
                }
				hashCode = (hashCode * 59) + CurrencySymbol.GetHashCode();
				hashCode = (hashCode * 59) + CurrencyName.GetHashCode();
                hashCode = (hashCode * 59) + CurrencyDecimalPlaces.GetHashCode();
                if (NativeCurrencyId != null)
                {
                    hashCode = (hashCode * 59) + NativeCurrencyId.GetHashCode();
                }
                if (NativeCurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + NativeCurrencyCode.GetHashCode();
                }
				hashCode = (hashCode * 59) + NativeCurrencySymbol.GetHashCode();
				hashCode = (hashCode * 59) + NativeCurrencyName.GetHashCode();
                hashCode = (hashCode * 59) + NativeCurrencyDecimalPlaces.GetHashCode();
                if (ForeignCurrencyId != null)
                {
                    hashCode = (hashCode * 59) + ForeignCurrencyId.GetHashCode();
                }
                if (ForeignCurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + ForeignCurrencyCode.GetHashCode();
                }
                if (ForeignCurrencySymbol != null)
                {
                    hashCode = (hashCode * 59) + ForeignCurrencySymbol.GetHashCode();
                }
                if (ForeignCurrencyDecimalPlaces != null)
                {
                    hashCode = (hashCode * 59) + ForeignCurrencyDecimalPlaces.GetHashCode();
                }
				hashCode = (hashCode * 59) + Description.GetHashCode();
                if (SourceId != null)
                {
                    hashCode = (hashCode * 59) + SourceId.GetHashCode();
                }
                if (SourceName != null)
                {
                    hashCode = (hashCode * 59) + SourceName.GetHashCode();
                }
                if (SourceIban != null)
                {
                    hashCode = (hashCode * 59) + SourceIban.GetHashCode();
                }
                hashCode = (hashCode * 59) + SourceType.GetHashCode();
                if (DestinationId != null)
                {
                    hashCode = (hashCode * 59) + DestinationId.GetHashCode();
                }
                if (DestinationName != null)
                {
                    hashCode = (hashCode * 59) + DestinationName.GetHashCode();
                }
                if (DestinationIban != null)
                {
                    hashCode = (hashCode * 59) + DestinationIban.GetHashCode();
                }
                hashCode = (hashCode * 59) + DestinationType.GetHashCode();
                if (BudgetId != null)
                {
                    hashCode = (hashCode * 59) + BudgetId.GetHashCode();
                }
                if (BudgetName != null)
                {
                    hashCode = (hashCode * 59) + BudgetName.GetHashCode();
                }
                if (CategoryId != null)
                {
                    hashCode = (hashCode * 59) + CategoryId.GetHashCode();
                }
                if (CategoryName != null)
                {
                    hashCode = (hashCode * 59) + CategoryName.GetHashCode();
                }
                if (BillId != null)
                {
                    hashCode = (hashCode * 59) + BillId.GetHashCode();
                }
                if (BillName != null)
                {
                    hashCode = (hashCode * 59) + BillName.GetHashCode();
                }
                hashCode = (hashCode * 59) + Reconciled.GetHashCode();
                if (Notes != null)
                {
                    hashCode = (hashCode * 59) + Notes.GetHashCode();
                }
                if (Tags != null)
                {
                    hashCode = (hashCode * 59) + Tags.GetHashCode();
                }
                if (InternalReference != null)
                {
                    hashCode = (hashCode * 59) + InternalReference.GetHashCode();
                }
                if (ExternalId != null)
                {
                    hashCode = (hashCode * 59) + ExternalId.GetHashCode();
                }
                if (ExternalUrl != null)
                {
                    hashCode = (hashCode * 59) + ExternalUrl.GetHashCode();
                }
                if (OriginalSource != null)
                {
                    hashCode = (hashCode * 59) + OriginalSource.GetHashCode();
                }
                if (RecurrenceId != null)
                {
                    hashCode = (hashCode * 59) + RecurrenceId.GetHashCode();
                }
                if (RecurrenceTotal != null)
                {
                    hashCode = (hashCode * 59) + RecurrenceTotal.GetHashCode();
                }
                if (RecurrenceCount != null)
                {
                    hashCode = (hashCode * 59) + RecurrenceCount.GetHashCode();
                }
                if (ImportHashV2 != null)
                {
                    hashCode = (hashCode * 59) + ImportHashV2.GetHashCode();
                }
                if (SepaCc != null)
                {
                    hashCode = (hashCode * 59) + SepaCc.GetHashCode();
                }
                if (SepaCtOp != null)
                {
                    hashCode = (hashCode * 59) + SepaCtOp.GetHashCode();
                }
                if (SepaCtId != null)
                {
                    hashCode = (hashCode * 59) + SepaCtId.GetHashCode();
                }
                if (SepaDb != null)
                {
                    hashCode = (hashCode * 59) + SepaDb.GetHashCode();
                }
                if (SepaCountry != null)
                {
                    hashCode = (hashCode * 59) + SepaCountry.GetHashCode();
                }
                if (SepaEp != null)
                {
                    hashCode = (hashCode * 59) + SepaEp.GetHashCode();
                }
                if (SepaCi != null)
                {
                    hashCode = (hashCode * 59) + SepaCi.GetHashCode();
                }
                if (SepaBatchId != null)
                {
                    hashCode = (hashCode * 59) + SepaBatchId.GetHashCode();
                }
                if (InterestDate != null)
                {
                    hashCode = (hashCode * 59) + InterestDate.GetHashCode();
                }
                if (BookDate != null)
                {
                    hashCode = (hashCode * 59) + BookDate.GetHashCode();
                }
                if (ProcessDate != null)
                {
                    hashCode = (hashCode * 59) + ProcessDate.GetHashCode();
                }
                if (DueDate != null)
                {
                    hashCode = (hashCode * 59) + DueDate.GetHashCode();
                }
                if (PaymentDate != null)
                {
                    hashCode = (hashCode * 59) + PaymentDate.GetHashCode();
                }
                if (InvoiceDate != null)
                {
                    hashCode = (hashCode * 59) + InvoiceDate.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
