/*
 * Firefly III API v6.4.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-10-28
 *
 * The version of the OpenAPI document: 6.4.2
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// UserGroupReadAttributes
    /// </summary>
    [DataContract(Name = "UserGroupReadAttributes")]
    public partial class UserGroupReadAttributes : IEquatable<UserGroupReadAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGroupReadAttributes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserGroupReadAttributes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGroupReadAttributes" /> class.
        /// </summary>
        /// <param name="title">Title of the user group. By default, it is the same as the user&#39;s email address..</param>
        /// <param name="primaryCurrencyCode">Returns the primary currency code of the user group..</param>
        /// <param name="members">members.</param>
        public UserGroupReadAttributes(string title = default(string), string primaryCurrencyCode = default(string), List<UserGroupReadMembers> members = default(List<UserGroupReadMembers>))
        {
            Title = title;
            PrimaryCurrencyCode = primaryCurrencyCode;
            Members = members;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        [JsonPropertyName("created_at")]
        [JsonInclude]
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Returns false as CreatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /// <example>2018-09-17T12:46:47+01:00</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = true)]
        [JsonPropertyName("updated_at")]
        [JsonInclude]
        public DateTime UpdatedAt { get; private set; }

        /// <summary>
        /// Returns false as UpdatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return false;
        }
        /// <summary>
        /// Is this user group (&#39;financial administration&#39;) currently the active administration?
        /// </summary>
        /// <value>Is this user group (&#39;financial administration&#39;) currently the active administration?</value>
        /// <example>false</example>
        [DataMember(Name = "in_use", EmitDefaultValue = true)]
        [JsonPropertyName("in_use")]
        [JsonInclude]
        public bool InUse { get; private set; }

        /// <summary>
        /// Returns false as InUse should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInUse()
        {
            return false;
        }
        /// <summary>
        /// Can the current user see the members of this user group?
        /// </summary>
        /// <value>Can the current user see the members of this user group?</value>
        /// <example>true</example>
        [DataMember(Name = "can_see_members", EmitDefaultValue = true)]
        [JsonPropertyName("can_see_members")]
        [JsonInclude]
        public bool CanSeeMembers { get; private set; }

        /// <summary>
        /// Returns false as CanSeeMembers should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCanSeeMembers()
        {
            return false;
        }
        /// <summary>
        /// Title of the user group. By default, it is the same as the user&#39;s email address.
        /// </summary>
        /// <value>Title of the user group. By default, it is the same as the user&#39;s email address.</value>
        /// <example>demo@firefly</example>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        [JsonPropertyName("title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the primary currency ID of the user group.
        /// </summary>
        /// <value>Returns the primary currency ID of the user group.</value>
        /// <example>12</example>
        [DataMember(Name = "primary_currency_id", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_id")]
        [JsonInclude]
        public string PrimaryCurrencyId { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyId()
        {
            return false;
        }
        /// <summary>
        /// Returns the primary currency code of the user group.
        /// </summary>
        /// <value>Returns the primary currency code of the user group.</value>
        /// <example>EUR</example>
        [DataMember(Name = "primary_currency_code", EmitDefaultValue = false)]
        [JsonPropertyName("primary_currency_code")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string PrimaryCurrencyCode { get; set; }

        /// <summary>
        /// Returns the primary currency symbol of the user group.
        /// </summary>
        /// <value>Returns the primary currency symbol of the user group.</value>
        /// <example>$</example>
        [DataMember(Name = "primary_currency_symbol", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_symbol")]
        [JsonInclude]
        public string PrimaryCurrencySymbol { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencySymbol should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencySymbol()
        {
            return false;
        }
        /// <summary>
        /// Returns the primary currency decimal places of the user group.
        /// </summary>
        /// <value>Returns the primary currency decimal places of the user group.</value>
        /// <example>2</example>
        [DataMember(Name = "primary_currency_decimal_places", EmitDefaultValue = true)]
        [JsonPropertyName("primary_currency_decimal_places")]
        [JsonInclude]
        public int PrimaryCurrencyDecimalPlaces { get; private set; }

        /// <summary>
        /// Returns false as PrimaryCurrencyDecimalPlaces should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrimaryCurrencyDecimalPlaces()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Members
        /// </summary>
        [DataMember(Name = "members", EmitDefaultValue = false)]
        [JsonPropertyName("members")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<UserGroupReadMembers> Members { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserGroupReadAttributes {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  InUse: ").Append(InUse).Append("\n");
            sb.Append("  CanSeeMembers: ").Append(CanSeeMembers).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  PrimaryCurrencyId: ").Append(PrimaryCurrencyId).Append("\n");
            sb.Append("  PrimaryCurrencyCode: ").Append(PrimaryCurrencyCode).Append("\n");
            sb.Append("  PrimaryCurrencySymbol: ").Append(PrimaryCurrencySymbol).Append("\n");
            sb.Append("  PrimaryCurrencyDecimalPlaces: ").Append(PrimaryCurrencyDecimalPlaces).Append("\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, FireflyIIINet.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as UserGroupReadAttributes);
        }

        /// <summary>
        /// Returns true if UserGroupReadAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of UserGroupReadAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserGroupReadAttributes input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    CreatedAt == input.CreatedAt ||
					CreatedAt.Equals(input.CreatedAt)
                ) &&
                (
                    UpdatedAt == input.UpdatedAt ||
					UpdatedAt.Equals(input.UpdatedAt)
                ) &&
                (
                    InUse == input.InUse ||
                    InUse.Equals(input.InUse)
                ) &&
                (
                    CanSeeMembers == input.CanSeeMembers ||
                    CanSeeMembers.Equals(input.CanSeeMembers)
                ) &&
                (
                    Title == input.Title ||
                    (Title != null &&
                    Title.Equals(input.Title))
                ) &&
                (
                    PrimaryCurrencyId == input.PrimaryCurrencyId ||
					PrimaryCurrencyId.Equals(input.PrimaryCurrencyId)
                ) &&
                (
                    PrimaryCurrencyCode == input.PrimaryCurrencyCode ||
                    (PrimaryCurrencyCode != null &&
                    PrimaryCurrencyCode.Equals(input.PrimaryCurrencyCode))
                ) &&
                (
                    PrimaryCurrencySymbol == input.PrimaryCurrencySymbol ||
					PrimaryCurrencySymbol.Equals(input.PrimaryCurrencySymbol)
                ) &&
                (
                    PrimaryCurrencyDecimalPlaces == input.PrimaryCurrencyDecimalPlaces ||
                    PrimaryCurrencyDecimalPlaces.Equals(input.PrimaryCurrencyDecimalPlaces)
                ) &&
                (
                    Members == input.Members ||
                    Members != null &&
                    input.Members != null &&
                    Members.SequenceEqual(input.Members)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
				hashCode = (hashCode * 59) + CreatedAt.GetHashCode();
				hashCode = (hashCode * 59) + UpdatedAt.GetHashCode();
                hashCode = (hashCode * 59) + InUse.GetHashCode();
                hashCode = (hashCode * 59) + CanSeeMembers.GetHashCode();
                if (Title != null)
                {
                    hashCode = (hashCode * 59) + Title.GetHashCode();
                }
				hashCode = (hashCode * 59) + PrimaryCurrencyId.GetHashCode();
                if (PrimaryCurrencyCode != null)
                {
                    hashCode = (hashCode * 59) + PrimaryCurrencyCode.GetHashCode();
                }
				hashCode = (hashCode * 59) + PrimaryCurrencySymbol.GetHashCode();
                hashCode = (hashCode * 59) + PrimaryCurrencyDecimalPlaces.GetHashCode();
                if (Members != null)
                {
                    hashCode = (hashCode * 59) + Members.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
