/*
 * Firefly III API v6.4.2
 *
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2025-10-28
 *
 * The version of the OpenAPI document: 6.4.2
 * Contact: james@firefly-iii.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FireflyIIINet.Client.OpenAPIDateConverter;

namespace FireflyIIINet.Model
{
    /// <summary>
    /// The possible roles of the user in this user group are documented here: https://docs.firefly-iii.org/references/firefly-iii/api/
    /// </summary>
    /// <value>The possible roles of the user in this user group are documented here: https://docs.firefly-iii.org/references/firefly-iii/api/</value>
    [JsonConverter(typeof(FireflyIIINet.Client.StringEnumMemberConverter))]
    public enum UserGroupReadRole
    {
        /// <summary>
        /// Enum Owner for value: owner
        /// </summary>
        [EnumMember(Value = "owner")]
        Owner = 1,

        /// <summary>
        /// Enum Ro for value: ro
        /// </summary>
        [EnumMember(Value = "ro")]
        Ro = 2,

        /// <summary>
        /// Enum MngTrx for value: mng_trx
        /// </summary>
        [EnumMember(Value = "mng_trx")]
        MngTrx = 3,

        /// <summary>
        /// Enum MngMeta for value: mng_meta
        /// </summary>
        [EnumMember(Value = "mng_meta")]
        MngMeta = 4,

        /// <summary>
        /// Enum ReadBudgets for value: read_budgets
        /// </summary>
        [EnumMember(Value = "read_budgets")]
        ReadBudgets = 5,

        /// <summary>
        /// Enum ReadPiggies for value: read_piggies
        /// </summary>
        [EnumMember(Value = "read_piggies")]
        ReadPiggies = 6,

        /// <summary>
        /// Enum ReadSubscriptions for value: read_subscriptions
        /// </summary>
        [EnumMember(Value = "read_subscriptions")]
        ReadSubscriptions = 7,

        /// <summary>
        /// Enum ReadRules for value: read_rules
        /// </summary>
        [EnumMember(Value = "read_rules")]
        ReadRules = 8,

        /// <summary>
        /// Enum ReadRecurring for value: read_recurring
        /// </summary>
        [EnumMember(Value = "read_recurring")]
        ReadRecurring = 9,

        /// <summary>
        /// Enum ReadWebhooks for value: read_webhooks
        /// </summary>
        [EnumMember(Value = "read_webhooks")]
        ReadWebhooks = 10,

        /// <summary>
        /// Enum ReadCurrencies for value: read_currencies
        /// </summary>
        [EnumMember(Value = "read_currencies")]
        ReadCurrencies = 11,

        /// <summary>
        /// Enum MngBudgets for value: mng_budgets
        /// </summary>
        [EnumMember(Value = "mng_budgets")]
        MngBudgets = 12,

        /// <summary>
        /// Enum MngPiggies for value: mng_piggies
        /// </summary>
        [EnumMember(Value = "mng_piggies")]
        MngPiggies = 13,

        /// <summary>
        /// Enum MngSubscriptions for value: mng_subscriptions
        /// </summary>
        [EnumMember(Value = "mng_subscriptions")]
        MngSubscriptions = 14,

        /// <summary>
        /// Enum MngRules for value: mng_rules
        /// </summary>
        [EnumMember(Value = "mng_rules")]
        MngRules = 15,

        /// <summary>
        /// Enum MngRecurring for value: mng_recurring
        /// </summary>
        [EnumMember(Value = "mng_recurring")]
        MngRecurring = 16,

        /// <summary>
        /// Enum MngWebhooks for value: mng_webhooks
        /// </summary>
        [EnumMember(Value = "mng_webhooks")]
        MngWebhooks = 17,

        /// <summary>
        /// Enum MngCurrencies for value: mng_currencies
        /// </summary>
        [EnumMember(Value = "mng_currencies")]
        MngCurrencies = 18,

        /// <summary>
        /// Enum ViewReports for value: view_reports
        /// </summary>
        [EnumMember(Value = "view_reports")]
        ViewReports = 19,

        /// <summary>
        /// Enum ViewMemberships for value: view_memberships
        /// </summary>
        [EnumMember(Value = "view_memberships")]
        ViewMemberships = 20,

        /// <summary>
        /// Enum Full for value: full
        /// </summary>
        [EnumMember(Value = "full")]
        Full = 21
    }

}
